### ISSUE TITLE
Solid backgrounds no longer accessible

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#1134]
**Distribution (run `cat /etc/os-release`):**
 
20.04 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Display background selector

**Issue/Bug Description:**

In previous OS versions, it was possible to select a solid background instead of a photo. This was really helpful because it could improve UI performance (due to fewer page faults, region fractures, etc.). It's also nice, sometimes, just to look at nothing instead of fragments of your shot off the balcony in Hawaii.

**Steps to reproduce (if you know):**

Bring up the background photo selector. Observe that the color menu is absent. (I wonder if this is a "feature", but it feels like a bug, like a menu list which was prematurely terminated.)

**Expected behavior:**

Give solid colors as an option, even if we have to choose from a limited selection

**Other Notes:**

When I do, in fact, select a photo it rounds off only the upper corners. This is weird because (1) it's inconsistent with the square corners at the bottom and (2) it's nonsensical because the system menu bar is above it, so it doesn't actually abut the corners of the screen (which aren't round on any laptop I've seen, anyway).

Workaround would be to save a monochrome photo of one's favorite background color. Dumb, but doable.

**Comment by jacobgkau** [comment]
Solid color options were removed from GNOME Control Center upstream, and there are not currently plans to bring them back: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/717 

In addition to the solid color picture workaround that you mentioned, you can still turn off the image background and then set the background to a hex code (color) using these commands:

```
gsettings set org.gnome.desktop.background picture-uri ''
gsettings set org.gnome.desktop.background primary-color '#a1b2c3'
```

The top corners are rounded at all times. This is not 'nonsensical' because the screen corners match the corners of windows, which are rounded on top and straight on the bottom. This is also a design decision by upstream GNOME; older versions of the Pop theme did not use rounded corners, but I believe this changed when it was rebased on Adwaita, which was done to increase compatibility with third-party applications and reduce visual breakage caused by theming: https://github.com/pop-os/gtk-theme/pull/322
