### ISSUE TITLE
Settings don't get saved, audio preferences for devices reset

### ISSUE THREAD

**Issue by mrbeaner** [pop-os/pop#1166]
Audio preferences for devices get reset every time I restart or start up the PC with latest POP_OS. Is there any way to fix this?
My microphone for some reason is set as speaker and my main audio device - HyperX headphones aren't the main audio output device and I need to set it to HyperX manually everytime I start the PC.
![Screenshot from 2020-07-29 00-15-39](https://user-images.githubusercontent.com/68926725/88722901-ad0a7300-d130-11ea-971e-05e4dd9ee0ed.png)

**Comment by StaZarycki** [comment]
I don't really think the issue is the same as in [#1016](https://github.com/pop-os/pop/issues/1016) since there's no change in devices being physically plugged in or out.

I managed to fix the issue by editing my default.pa file:
`sudo vim /etc/pulse/default.pa` (you can use gpedit or nano or wahtever)

Then at the very bottom of the file I uncommented `#set-default-sink` and `#set-default-source` and changed the device names to what I could see by typing `pacmd list-sinks` and `pacmd list-sources`. So that's how these lines look like for me right now:

`set-default-sink alsa_output.pci-0000_00_1b.0.analog-stereo`
`set-default-source alsa_input.usb-0d8c_C-Media_USB_Audio_Device-00.mono-fallback`

Hope it helped!
