### ISSUE TITLE
can't access to bios , Acer swift 3 SF314-52G Insydeh20 bios utility

### ISSUE THREAD

**Issue by sgsdev** [pop-os/pop#1180]
bios isn't accessible after dual boot with windows 10 (2004) blank screen , single underscore character at top left corner
secure boot is disabled, i made large 1gb partition for boot/efi,  installed Pop first , also tried install windows first with large boot/efi partiton during setup (shift f10 via command prompt ) same result 
f12 works fine , i can see both Pop and windows boot entries

**Comment by jacobgkau** [comment]
Accessing the BIOS/UEFI menu would most likely have to do with your hardware, since that happens before the OS is booted. What makes you think this is related to Pop!_OS? Have you contacted Acer support about this?

Have you disabled Fast Startup within your Windows installation?

If you're referring to the bootloader menu and not the BIOS/UEFI menu, you would want to hold down spacebar to access systemd-boot on a UEFI machine, or ESC to access GRUB on a legacy BIOS machine.

**Comment by sgsdev** [comment]
I think the problem is with systemd config and my laptop firmware, yes I
have disabled fast startup , dual boot with grub works without any problems

**Comment by mmstick** [comment]
systemd and Linux has no control over the firmware setup interface, as these only execute long after POST.

**Comment by filippofontana** [comment]
I have the same laptop and the same problem too. In order to give some context, after the Pop OS installation even Windows started to behave weirdly. For example, the startup programs menu in the Task Manager became empty and the programs listed there were no longer accessible. The real problem is that if you can't access the BIOS, it is not possible to set Pop OS as first entry and every time you have to press the F12 button (also for me it works) to select the OS to boot. Another friend of mine with the same laptop model has exactly the same problems reported. As already mentioned, the problem appears only with "systemd based" OSs, previously I had an Elementary OS installation with GRUB and it worked without problems. So do you say that it's only a problem related to this specific laptop series?

**Comment by AayushBangroo** [comment]
> I have the same laptop and the same problem too. In order to give some context, after the Pop OS installation even Windows started to behave weirdly. For example, the startup programs menu in the Task Manager became empty and the programs listed there were no longer accessible. The real problem is that if you can't access the BIOS, it is not possible to set Pop OS as first entry and every time you have to press the F12 button (also for me it works) to select the OS to boot. Another friend of mine with the same laptop model has exactly the same problems reported. As already mentioned, the problem appears only with "systemd based" OSs, previously I had an Elementary OS installation with GRUB and it worked without problems. So do you say that it's only a problem related to this specific laptop series?

Exactly same issue I am facing. If I try to enter bios it shows a black screen with non blinking underscore. However I am able to access it using f12

**Comment by luca-morellini** [comment]
> I have the same laptop and the same problem too. In order to give some context, after the Pop OS installation even Windows started to behave weirdly. For example, the startup programs menu in the Task Manager became empty and the programs listed there were no longer accessible. The real problem is that if you can't access the BIOS, it is not possible to set Pop OS as first entry and every time you have to press the F12 button (also for me it works) to select the OS to boot. Another friend of mine with the same laptop model has exactly the same problems reported. As already mentioned, the problem appears only with "systemd based" OSs, previously I had an Elementary OS installation with GRUB and it worked without problems. So do you say that it's only a problem related to this specific laptop series?

I have the same issue too. I tried pop os and arch linux and both doesn't let me access to the bios. I tried with ubuntu and everything works fine. Is there someone who solved the problem?
