### ISSUE TITLE
monitor colour is very bright and high contrast and screen tearing problem

### ISSUE THREAD

**Issue by lordofwizard** [pop-os/pop#1258]
**Distribution (run `cat /etc/os-release`):**
 
 POP OS 20.04 LTS release updated packages and kernel on sat sept 26 8.43
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Purchase new GPU to day AMD rx 570 g1 Gaming.
I have been using intel hd 630 before on my i3 7100 cpu.
The problem is that when i installed the gpu the colours are very bright and vibrant also on my black wallpaper i can actually see some black brownish boxes. I have installed the intel + amd version of pop os. Also while watching youtube i found some screen tearing problems( video and image links are attached).

**Steps to reproduce (if you know):**
Well i did the xorg config for the problem by watching this tutorial link is provided downbelow.

**Expected behavior:**
1. Fix the colour problem and the screen tearing problem.

**Other Notes:**
https://www.youtube.com/watch?v=WWg8q_f7nI4&ab_channel=NeonCipher

![20200926_205142](https://user-images.githubusercontent.com/38832648/94344118-b9c91b80-003a-11eb-9304-f31882303615.jpg)
![20200926_205148](https://user-images.githubusercontent.com/38832648/94344122-bfbefc80-003a-11eb-9465-124161ff931b.jpg)
https://drive.google.com/file/d/1wvejI_LQdq1--9qAqpOhLbWuT2PJr2p0/view?usp=sharing

PLEASE HELP I NEED IT TO BE GOOD. PLEASE GUYS HELP ME. MY FATHER WILL RETURN THE GPU OTHERWISE.

**Comment by leviport** [comment]
I might be missing it, but I can't tell what the issue is in those pictures of your display. Could you please describe those in a little more detail, and maybe see if you can demonstrate them more clearly in photos?

I can see the issue in the video you linked, however, and it makes me wonder if that is related to https://github.com/pop-os/shell/issues/566. Do you only see those sorts of graphical artifacts in Chromium/Chrome, or does Firefox do the same sort of thing?

**Comment by AndreaMonzini** [comment]
Hello,
about video tearing in my AMDGPU system i solve with this procedure:

`cd /usr/share/X11/xorg.conf.d`
and edit the file `10-amdgpu.conf `  adding a new line with `Option "TearFree" "on"`
This solve my Video Tearing problems.
