### ISSUE TITLE
No Alert Sound section in Gnome Settings

### ISSUE THREAD

**Issue by ScrambleTheRamble** [pop-os/pop#1266]
In 20.04 it seems to be impossible to change the Alert Sounds from the gnome-settings app, this means users can not easily change these.

**Comment by izetter** [comment]
Why nobody else commented on this? the problem persists on 22.04 and alerts do not emit any sound!

**Comment by leviport** [comment]
@izetter this issue is not describing the problem you're describing. In 20.04, the notification sound selector was removed from Gnome Control Center since Pop got its own custom (and much better) sound theme. This required removing the old sound selector entirely.

I recommend installing dconf-editor and checking that `/org/gnome/desktop/sound/event-sounds` is set to the default value of "true". If you still don't get sound theme sounds after that, and your audio is otherwise working as expected, open a bug report in https://github.com/pop-os/gtk-theme/issues
