### ISSUE TITLE
Laptop hangs on reboot

### ISSUE THREAD

**Issue by piazzai** [pop-os/pop#1282]
I am running Pop_OS 20.04. I bought my Serval WS last month and I've been using it for a few days.
 
I was typing in Atom when all of a sudden the cursor kept moving right, as if someone was holding down the arrow key. It was as if this perpetual input was blocking out all other input. With some difficulties, I instructed the system to restart, but it froze on a black screen before rebooting. The power button does not respond (which is absurd), so I am left with no option but to wait for the battery to drain.

I wasn't doing any computationally intensive tasks. I had an ereader plugged into one USB for charging, and an external fan plugged into another. I set FlexiCharger in the BIOS to hold the battery at no more than 90%.

This is really frustrating and I hope a fix exists. Not a fan of waiting for hours until I can use my laptop again (and who knows for how long).

**Comment by jacobgkau** [comment]
> I bought my Serval WS last month and I've been using it for a few days.

I'm sorry for the trouble. If you own a System76 machine, it's best to open a ticket with our [support team](https://support.system76.com/), since they can assist you with both software and hardware. If this is a hardware defect, they can have the machine repaired or the appropriate components replaced under your warranty.

> The power button does not respond (which is absurd), so I am left with no option but to wait for the battery to drain.

Even holding down the power button for 10-20 seconds didn't make the machine power off? That sounds like an issue with the motherboard or its firmware, not something we can fix in software.

Rather than waiting for the battery to drain, you should also be able to [remove it](https://tech-docs.system76.com/models/serw12/repairs.html) since it's held onto the system with two regular Phillips screws. That would cut power to the system, shutting it off (as long as the power cable's disconnected first.)

> This is really frustrating and I hope a fix exists. Not a fan of waiting for hours until I can use my laptop again (and who knows for how long).

Again, I would highly recommend reaching out to support using the link above. If you can open the System76 Driver app, click Create Log Files, and upload the resulting file from your home folder to the support case (you may need to do this separately from the initial message), that may include information to determine whether this is a hardware issue and why you were experiencing the input issue.
