### ISSUE TITLE
Partition encryption does not allow modification of partition

### ISSUE THREAD

**Issue by Joesplace** [pop-os/pop#1456]
**(1) Issue/Bug Description:**
I selected to encrypt my hard drive while installing POP! OS 20.10 and now can't shrink or grow the partition. I even tried booting from a POP USB and signing in to this partition. GParted allows you to Deactivate the partition but still can't modify it.

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**
I expected to modify encrypted partition as needed.

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 1.1.0~1608318806~20.10~19ebae0
  Candidate: 1.1.0~1608318806~20.10~19ebae0
  Version table:
 *** 1.1.0~1608318806~20.10~19ebae0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by leviport** [comment]
Resizing LUKS partitions is still possible, it's just a bit more complicated process. This isn't exactly a bug, as much as a caveat of using LUKS encryption. There are quite a few [resources online](https://unix.stackexchange.com/questions/609169/how-to-resize-a-luks-device-revisited) about how to resize LUKS partitions, so I would refer you to those if it's something you'd like to explore. Otherwise, it may be easiest just to back up their contents, reformat the drive, then migrate your backed up data back into them.
