### ISSUE TITLE
oryp6: Waking up doesn't always work

### ISSUE THREAD

**Issue by willir** [pop-os/pop#1469]
**Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
``` 

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**

Sometimes it cannot properly wake up after sleep. It gets to login screen, but nothing works after it.
So I have to hard reboot.

The only things that I notice working are:

1. Chaning keyboard lights - via `fn` and numpad keys
2. Turning on/off screen (`fn-F2`)

**Steps to reproduce (if you know):**

Went to sleep via either:

1. Closing the lit
2. Pressing sleep button (fn-F12)
3. Waiting some time (usually more than 10 minutes, hard to tell how long exactly)
4. Try to wake up by pressing any keyboard buttons
5. Wait for login screen to appear
6. Try to do press buttons to get password form (it doesn't appear)

I should point out that sometimes it works, maybe 50%. 

**Expected behavior:**

Properly waking up.

**Other Notes:**

My laptop is System76 Oryx Pro.

I think similar problem I can get if I run `systemctl restart systemd-logind.service`.

Here are some logs:

1. This one is for boot that wouldn't wakeup [previous-boot.journalctl.log (`sudo journalctl -b-1`)](https://github.com/pop-os/pop/files/5759174/previous-boot.journalctl.log)
2. This is is for boot right after one that wouldn't wakeup [current-boot.journalctl.log (`sudo journalctl -b`)](https://github.com/pop-os/pop/files/5759173/current-boot.journalctl.log)
3. [dmidecode.log](https://github.com/pop-os/pop/files/5759176/dmidecode.log)

**Comment by willir** [comment]
It seems the same problem can happen on restoring from hibernation.
inserting an external keyboard/mouse didn't help.

Pressing `Ctrl+Alt+F3` to switch to a different terminal didn't do anything either.

**Comment by willir** [comment]
I was able to get logs when problems occur on `sudo systemctl restart systemd-logind.service`: [journalctl-restart-systemd-logind.log](https://github.com/pop-os/pop/files/5761840/journalctl-restart-systemd-logind.log)

Restarting happens at:

```
Jan 03 10:49:04 pop-os sudo[5320]:   willir : TTY=pts/0 ; PWD=/home/willir ; USER=root ; COMMAND=/usr/bin/systemctl restart systemd-logind.service
```

I guess something interesting happens here:

```
Jan 03 10:49:04 pop-os systemd[1867]: Starting GNOME Shell on X11...
Jan 03 10:49:04 pop-os polkitd(authority=local)[997]: Unregistered Authentication Agent for unix-session:2 (system bus name :1.92, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Jan 03 10:49:04 pop-os gdm-launch-environment][5326]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jan 03 10:49:04 pop-os gnome-shell[5338]: Failed to create backend: Unable to open display ':1'
Jan 03 10:49:04 pop-os systemd[1867]: org.gnome.Shell@x11.service: Failed with result 'protocol'.
Jan 03 10:49:04 pop-os systemd[1867]: Failed to start GNOME Shell on X11.
Jan 03 10:49:04 pop-os systemd[1867]: org.gnome.Shell@x11.service: Scheduled restart job, restart counter is at 2.
Jan 03 10:49:04 pop-os systemd[1867]: Stopped GNOME Shell on X11.
```

**Comment by borjaevo** [comment]
Are you able to see login screen after switching from terminal?
I have a similar problem, black screen. But if i switch to terminal (for example ctrl + alt + F3) and go back to gnome (ctrl + alt + f1) i can see login screen. But after login it goes all black again. 
I have to reboot the computer every time it happens this to me, and its most of the times i suspend the computer.

**Comment by willir** [comment]
@borjaevo, no. `Ctrl+Alt+F3` doesn't work for me.

**Comment by jacobgkau** [comment]
> My laptop is System76 Oryx Pro.

I'm sorry about the suspend/resume issues. If you're having the problem on System76 hardware, you should open a [support ticket](https://support.system76.com) so they can help you troubleshoot this directly. Suspend/resume issues can indicate hardware problems, and they can also diagnose and correct that if it's the cause.

Some information that would be useful to narrow down the issue (which support may ask for):
- Does the issue occur in NVIDIA mode, Integrated/Intel mode, or both?
- Does the issue occur while booted into Pop!_OS Recovery (or a Pop!_OS live disk?)

> It gets to login screen, but nothing works after it.

> 6. Try to do press buttons to get password form (it doesn't appear)

It almost sounds like it's suspending/resuming, but the keyboard isn't working after resume. If you press Fn-F12 to suspend again, then resume again, are you able to log in again? If you run this command:

> sudo kernelstub -a i8042.nomux

Then reboot, does the issue still occur?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by ArjunSingh99** [comment]
> > My laptop is System76 Oryx Pro.
> 
> I'm sorry about the suspend/resume issues. If you're having the problem on System76 hardware, you should open a [support ticket](https://support.system76.com) so they can help you troubleshoot this directly. Suspend/resume issues can indicate hardware problems, and they can also diagnose and correct that if it's the cause.
> 
> Some information that would be useful to narrow down the issue (which support may ask for):
> 
> * Does the issue occur in NVIDIA mode, Integrated/Intel mode, or both?
> * Does the issue occur while booted into Pop!_OS Recovery (or a Pop!_OS live disk?)
> 
> > It gets to login screen, but nothing works after it.
> 
> > 1. Try to do press buttons to get password form (it doesn't appear)
> 
> It almost sounds like it's suspending/resuming, but the keyboard isn't working after resume. If you press Fn-F12 to suspend again, then resume again, are you able to log in again? If you run this command:
> 
> > sudo kernelstub -a i8042.nomux
> 
> Then reboot, does the issue still occur?
> 
> System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

I don't think this is a hardware issue, nor is it limited to system76 hardware. It's a common issue, as mentioned in #1381 and #1385.

**Comment by jacobgkau** [comment]
> I don't think this is a hardware issue, nor is it limited to system76 hardware. It's a common issue, as mentioned in #1381 and #1385.

Suspend/resume issues are usually a symptom, not a cause. If all three of these issues were caused by the same thing, then two of them would be closed as duplicates.

Additionally, https://github.com/pop-os/pop/issues/1381 says "the screen turns off, and I can't turn it back on." https://github.com/pop-os/pop/issues/1385 just says "Unable to type." Those are two different symptoms.

Some hardware requires the `i8042.nomux` kernel parameter to bring the keyboard back consistently after suspend/resume. The oryp6 didn't seem to need that option during pre-launch testing, but sometimes it becomes apparent that the option is needed as more widespread usage occurs and/or as the hardware ages. If the issue being reported here is that the keyboard doesn't work after suspend/resume, and if the option helps on the reporter's oryp6, then we could potentially add that option to the System76 Driver package to be applied on all oryp6 machines. Otherwise, if there's an oryp6 that's not suspend/resuming reliably at all (not just the keyboard, but the entire machine), we'd be fairly confident that's a hardware issue as we know the oryp6 supports suspend/resume with the software we're shipping. We cannot have that confidence for non-System76 hardware that we don't test on.

**Comment by evilthreads669966** [comment]
I posted this 3 months ago. Unable to Login after Sleep #1385
First off it does wake up. Waking up has absolutely nothing to do with logging in. I would love to get a response from you guys. Your operating system is bug ridden in regards to drivers. I recently updated and my sound is no longer the same quality either. So for you guys to chose this issue to respond to makes me wonder as the title of the issue is irrelevant to the main issue. As a matter of a fact it's completely off topic.

**Comment by evilthreads669966** [comment]
My apology as I didn't read your response completely @jacobgkau

**Comment by willir** [comment]
Hi, thanks for the responses! Sorry I haven't answered earlier.

> Does the issue occur in NVIDIA mode, Integrated/Intel mode, or both?

It definitely occurred in Integrated and Intel modes. I haven't tried NVIDIA mode yet.

> Does the issue occur while booted into Pop!_OS Recovery (or a Pop!_OS live disk?)

Haven't tried that yet :-(, I will post once I've tried. The problem with this issue, it doesn't occur after each wake-up. So it is harder to test.

> I'm sorry about the suspend/resume issues. If you're having the problem on System76 hardware, you should open a support ticket so they can help you troubleshoot this directly. Suspend/resume issues can indicate hardware problems, and they can also diagnose and correct that if it's the cause.

Thanks for the good advice. The only thing that stops me from doing so is -- pretty much the same problem occurs if I just `systemctl restart systemd-logind.service`, could it be hardware too?

> It almost sounds like it's suspending/resuming, but the keyboard isn't working after resume. If you press Fn-F12 to suspend again, then resume again, are you able to log in again? If you run this command:

I've tried pressing `Fn-F12`, it does nothing. Only things that seem to work:

1. Changing keyboard lights - via fn and Numpad keys
2. Turning on/off screen (`Fn-F2`)

An external keyboard doesn't work too.

**Comment by willir** [comment]
I've tried _Pop!_OS Recovery_, I couldn't make the issue be reproduced during wake-up. But it doesn't always reproduce in normal boot either. Maybe it needs to be in sleep for some time. However, `sudo systemctl restart systemd-logind.service` in _Pop!_OS Recovery_ did reproduce the issue.

Also, I think the wake-up issue doesn't appear in Windows.

**Comment by jacobgkau** [comment]
> pretty much the same problem occurs if I just `systemctl restart systemd-logind.service`, could it be hardware too?

I can make the keyboard/touchpad stop working (including `Fn-F12`) by restarting `systemd-logind.service` on any machine. I don't think that's related to a failure to resume from suspend.

Are you sure `Fn-F12` doesn't work after a failure to resume from suspend, or was all of the information from your last couple of messages gathered after restarting `systemd-logind`?

> I've tried _Pop!OS Recovery, I couldn't make the issue be reproduced during wake-up. But it doesn't always reproduce in normal boot either.

Figuring out whether the issue ever occurs in Recovery/live disk is an important step in determining whether it's an issue with hardware/software or configuration. I understand it can be difficult to troubleshoot intermittent problems. Logs from the System76 Driver app just after a failure to resume might be helpful to see where the issue lies, although again, it would be more appropriate to submit those in a support ticket since this is presumably machine-specific.

Looking back through the logs you already provided, I see "pixel saver" having some issues as the machine is suspending:

```
Jan 01 00:58:35 pop-os gnome-shell[2729]: == Stack trace for context 0x563a55792220 ==
Jan 01 00:58:35 pop-os gnome-shell[2729]: #0   563a56cc3e80 i   /home/willir/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:110 (faa9fa88740 @ 30)
```

So I would try disabling that extension if you haven't ruled it out already.

**Comment by willir** [comment]
> I can make the keyboard/touchpad stop working (including `Fn-F12`) by restarting `systemd-logind.service` on any machine. I don't think that's related to a failure to resume from suspend.

I see, so it is an expected behaviour?

> Are you sure `Fn-F12` doesn't work after a failure to resume from suspend, or was all of the information from your last couple of messages gathered after restarting `systemd-logind`?

Hmm.. I feel confident with that, though maybe now not 100%.

The thing is, it seems I don't get any suspend resume issues anymore for at least a week.

I'm not sure what caused the fix.

One thing I remember - I reverted back some of my changes for `suspend-then-hibernate`

It used to be something like this:
```
HandleLidSwitch=suspend-then-hibernate
HandleLidSwitchExternalPower=suspend-then-hibernate
HibernateDelaySec=2
```

I set small delay to test whether it works; at first I had tried without delay or with delay equal 30 or 60 seconds, but it didn't hibernate. I guess it is another bug I can file a support ticket, if it might machine specific as well.

P.S. Hibernate itself works (`sudo systemctl hibernate`). And I had same wakeup issue restoring from hibernate once.

P.P.S About `pixel saver`. I guess it could beak something, however, now when wakeup works fine `pixel saver` is enabled and I see those stacktrace logs/crashes in `journalctl`. So probably not just `pixel saver` along.

**Comment by jacobgkau** [comment]
Hibernation is not configured out-of-the-box in Pop!_OS and isn't something we typically test against right now, so if you were attempting to suspend-then-hibernate (which was not mentioned earlier in the issue), then I'm afraid that's not something I'd expect to work in the first place. Suspend means suspending to RAM, and that is what we ensure works on our machines.

Another issue came to my attention that sounds similar to what you're experiencing, but I can't be sure: https://github.com/pop-os/nvidia-graphics-drivers/issues/71 That other issue never happens in Integrated mode, while this issue was happening in Integrated mode, so I'm inclined to think this issue is unrelated to that one, but I wanted to mention it since it's for the same model.

Please let us know if the issue with regular suspend comes back. Otherwise, if it seems like it's limited to suspend-then-hibernate, we can rename this issue appropriately and some additional details about how you configured hibernation might be helpful. (The only other issue this could be grouped with for hibernation is https://github.com/pop-os/pop/issues/1184, but that one sounds like they're able to log in and their computer is just rebooting, so not the same symptoms.)

**Comment by willir** [comment]
After several weeks using sleep I had no issues. It works well.
I also used hibernation directly (https://github.com/arelange/gnome-shell-extension-hibernate-status) it works well too.

I guess I can try to set `suspend-then-hibernate` again and see whether it breaks everything.  
Or it isn't really going to work?

**Comment by willir** [comment]
I had no issues since then. So I guess it makes sense to close the issue

**Comment by banifou22** [comment]
Hi,
I have the same problem described here on Pop-OS 22.04.
I read this thread but I'm not sure what to do to get rid of this annoying issue. Please advice.
