### ISSUE TITLE
Fastboot commands don't work properly on Pop!_OS 20.04

### ISSUE THREAD

**Issue by JeffRockatansky** [pop-os/pop#1477]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
fastboot:
  Installed: 1:8.1.0+r23-5ubuntu2
  Candidate: 1:8.1.0+r23-5ubuntu2
  Version table:
 *** 1:8.1.0+r23-5ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
```

```
user@pop-os:~$ fastboot --version
fastboot version 1:8.1.0+r23-5ubuntu2
Installed as /usr/lib/android-sdk/platform-tools/fastboot
```

But this one seems outdated, so I also tried [latest binary](https://developer.android.com/studio/releases/platform-tools):
```
user@pop-os:~/Downloads$ ./platform-tools/fastboot --version
fastboot version 30.0.5-6877874
Installed as /home/user/Downloads/platform-tools/fastboot
```

**Issue/Bug Description:**
Trying to flash custom ROM and recovery on a smatrphone using my laptop running Pop!_OS 20.04. `adb` commands work mostly fine, smartphone successfully enters bootloader mode via `adb reboot bootloader`, but `fastboot boot boot.img` doesn't, it just freezes infinitely:
```
user@pop-os:~/Downloads$ sudo ./platform-tools/adb devices
List of devices attached
ZY225FHC2L	device

user@pop-os:~/Downloads$ sudo ./platform-tools/adb reboot bootloader
user@pop-os:~/Downloads$ sudo ./platform-tools/fastboot devices
ZY225FHC2L	fastboot
user@pop-os:~/Downloads$ sudo ./platform-tools/fastboot boot ./moto_g7+/twrp-3.5.0-lake-v1.img
Sending 'boot.img' (28704 KB)                      
```
And this never finishes.

* PC: laptop Dell Inspiron 7559 15'' (Intel i7, Nvidia GTX 960M)
* Smartphone: Motorola Moto G7 Plus (codename `lake`), bootloader unlocked
* ROM: LineageOS 17.1 ([dev build](https://downloads.kaotic.dev/LineageOS/lake/) from @Jleeblanch, confirmed to work)
* Recovery: TWRP 3.5.0 ([dev build](https://downloads.kaotic.dev/TWRP/lake/) from @Jleeblanch, confirmed to work)

**Steps to reproduce (if you know):**
1. Install (`sudo apt-get install android-tools-adb android-tools-fastboot`) **OR** [download](https://developer.android.com/studio/releases/platform-tools) `platform-tools`
2. Connect `lake` or similar Android smartphone (preferably w/ ab-slots and Type-C) to a Dell Inspiron 7559 laptop or similar laptop or PC via USB 2.0 or 3.0
3. Enter bootloader mode on smartphone via `adb reboot bootloader`
4. Try `fastboot boot twrp-3.5.0-lake-v2.img` or `fastboot boot twrp.img` for your device.

**Expected behavior:**
Smartphone to boot successfully into TWRP recovery.

**Other Notes:**
* On Windows 10 it worked fine for me.
* People online confirmed it to work on other Linux distributions (in particular, Ubuntu 20.04 and Xubuntu 20.10)
* For others it worked fine both using USB 2.0 and 3.0.
* `adb devices` and `fastboot devices` work fine

**Comment by bflanagin** [comment]
@JeffRockatansky thanks for the detailed reporting. In your bug description you're issuing the tools found in platform-tools and not the system supplied versions. Did you try the system supplied version as well?

**Comment by JeffRockatansky** [comment]
> system supplied version

If you mean those that are installed as packages via `apt` from Ubuntu `universe` repo then yes, tried those too with same results - they don't work in the same way. And they seem to be out of date for a long time.

**Comment by JeffRockatansky** [comment]
@bflanagin do you need any other info? Maybe logs of certain modules & apps?

**Comment by JeffRockatansky** [comment]
Any progress on this issue? Should I try to do something?

**Comment by JeffRockatansky** [comment]
Will try to reproduce this issue on the same machine running updated Pop!_OS 20.04. Hope it works now.

**Comment by JeffRockatansky** [comment]
Everything works now! Can you tell me what was the bug?

**Comment by jacobgkau** [comment]
Glad to hear it's working now! As you can see in your `apt policy` output, we do not maintain this package, it is coming from [Ubuntu](https://packages.ubuntu.com/focal/fastboot). Looking at the [Ubuntu changelog](https://changelogs.ubuntu.com/changelogs/pool/universe/a/android-platform-system-core/android-platform-system-core_8.1.0+r23-5ubuntu2/changelog), there haven't been any updates since early last year, so the fix must have been elsewhere (especially because the issue was also occurring with Google/Android's distribution of `platform-tools`.)

Since you found other people online "confirming" that it worked with Ubuntu 20.04 but you did not try yourself, I can't say whether it was another component in Ubuntu/Pop or something more specific to your own environment that was causing the problem before.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by syedadil2k19** [comment]
I'm facing the exact same issue at present with my Pop!_OS 20.04. But I wouldn't say that this issue is specific to Pop as I tried, unsuccessfully, in the older Kubuntu 18.04 on another device with the same result. Using Windows 10 however, I was able successfully flash the recovery & ROM using the same cables (which i thought was the issue).

I used only the latest binaries of `adb` & `fastboot` from Google, which is the recommended approach.


- PC: laptop Lenovo B40-80 (Intel i5)
- Smartphone: Asus Zenfone Max Pro M1 (ZB601KL/X00TD), bootloader unlocked
- ROM: Pixel Experience 11 (Plus) (Official for X00TD)
- Recovery: Pixel Experience 11 (Plus) accompanying recovery image (Official for X00TD)


`fastboot` version:

```
user@pop-os:~/Android/platform-tools$ sudo ./fastboot --version
fastboot version 31.0.3-7562133
Installed as /home/user/Android/platform-tools/fastboot
```

So the issue (in Ubuntu/Linux or Android `platform-tools`) is not really solved?

**Comment by JeffRockatansky** [comment]
@jacobgkau seems that this issue should be re-opened.

**Comment by syedadil2k19** [comment]
have posted the issue on [Unix StackExchange](https://unix.stackexchange.com/q/684494) and [Android StackExchange](https://android.stackexchange.com/q/244571)

**Comment by alanszlosek** [comment]
@JeffRockatansky I encountered this issue on both Pop 22.04 AND Ubuntu 22.04, and found that waiting to connect the device until after I run the command is what worked for me. See the link below for more info.

@syedadil2k19 I posted an answer to your Unix StackExchange question here: https://unix.stackexchange.com/a/732659/139574

Hope this works for both of you.

**Comment by ayelsew** [comment]
New updates!

I had test using Ubuntu 22.04.2 LTS, as a guest in KVM over my Pop!_OS 22.04 LTS. So I just redirect the USB device port to VM.

The fastboot works! Recognize and send commands without freezing.

```
❯ fastboot --version
fastboot version 28.0.2-debian /* From br.archive.ubuntu.com */
Installed as /usr/lib/android-sdk/platform-tools/fastboot

❯ fastboot devices
xxxxxxxxxx	 Motorola Fastboot Interface

❯ fastboot boot twrp.img
Sending 'boot.img' (26750 KB)                      OKAY [  2.013s]
Booting                                            OKAY [  0.872s]
Finished. Total time: 2.939s
```

And in the syslog of Ubuntu 22.04.2 LTS, we had a difference:
 
```
May 30 11:35:20 ubuntu kernel: [ 7980.142027] usb 1-3: new high-speed USB device number 5 using xhci_hcd
May 30 11:35:21 ubuntu kernel: [ 7980.420893] usb 1-3: New USB device found, idVendor=22b8, idProduct=2e80, bcdDevice= 1.00
May 30 11:35:21 ubuntu kernel: [ 7980.420901] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
May 30 11:35:21 ubuntu kernel: [ 7980.420905] usb 1-3: Product: Fastboot channel S
May 30 11:35:21 ubuntu kernel: [ 7980.420907] usb 1-3: Manufacturer: Motorola Inc.
May 30 11:35:21 ubuntu kernel: [ 7980.420910] usb 1-3: SerialNumber: xxxxxxxxxx
May 30 11:35:21 ubuntu mtp-probe: checking bus 1, device 5: "/sys/devices/pci0000:00/0000:00:02.1/0000:02:00.0/usb1/1-3"
May 30 11:35:21 ubuntu mtp-probe: bus: 1, device: 5 was not an MTP device
May 30 11:35:21 ubuntu mtp-probe: checking bus 1, device 5: "/sys/devices/pci0000:00/0000:00:02.1/0000:02:00.0/usb1/1-3"
May 30 11:35:21 ubuntu mtp-probe: bus: 1, device: 5 was not an MTP device
```

The system tried to mount as MTP... okay, but we don't have error message from fwupd like on pop-os!

**Comment by jacobgkau** [comment]
> I had tested using Ubuntu 22.04.2 LTS, as a guest in KVM over my Pop!_OS 22.04 LTS. So I just redirect the USB device port to VM.
> 
> The fastboot works! Recognize and send commands without freezing.

Maybe a silly question, but have you tried using Pop!_OS as a KVM guest in the same configuration? To make sure that you didn't fix it just with KVM versus by using Ubuntu (since previous commenters reported that they also had trouble in Ubuntu.)

**Comment by ayelsew** [comment]
@jacobgkau, no, I didn't.
But I coming with good news. 

At second time I tried to handle the fastboot CLI on Ubuntu, the same error of Pop OS started to appear at Ubuntu.
So I started to searching about fwupd, and I realize that it's a tool to update firmware and it has a daemon that listens to new devices attached in "fastboot mode".

## The cause
In a recent version of fwupd was introduced support to update firmware of some vendors like Lenovo that had bought Motorola. 

So when we attache the phone Motorola (in my case G7 Play and @JeffRockatansky  with G7 Plus), the fwupd daemon tries to recognize the device bootloader of this vendor by the command `getvar version-bootloader`, But that fastboot mode isn't the type supported by fwupd, because android don`t have the `version-bootloader` variable and here starts the bug.

So fwupd throw the error `failed to add device ...: failed to getvar version-bootloader: no response to read`, and it isn't unable to hangup the devices port. Now fastboot CLI of android can recognize the device in fastboot mode, but when we send command to the device, fastboot CLI wait for fwupd hangup to do it, but never happen. ("freezing command")

More about you can look here: https://github.com/fwupd/fwupd/issues/3187

## Solution (my solution)

I just removed all the package fwupd, but I really removed, not disable like they said in the issue https://github.com/fwupd/fwupd/issues/3187

Probably a downgrade to a version that don't add those vendors could solve too.

Now any version of fastboot CLI is working in Ubuntu and Pop OS!

**Comment by jacobgkau** [comment]
That's very helpful to know. Maybe this is a fwupd bug at this point. (This issue was opened back on January 8th, 2021, and I'm not sure how recent you mean by "recent version" for those vendors being added.)

I do see that https://github.com/fwupd/fwupd/issues/3187 was closed back in 2021, and we have a `fwupd` version from within the last month in Pop!_OS right now (see https://github.com/pop-os/fwupd).

**Comment by jacobgkau** [comment]
> I just removed all the package fwupd,

@ayelsew How did you remove `fwupd` without breaking your dependency tree? E.g. this happens by default if someone attempts to remove `fwupd` on Pop!_OS:

```
jacob@serw12:~$ sudo apt remove fwupd
[sudo] password for jacob: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Depends: fwupd but it is not going to be installed
               Depends: fwupdate
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by ayelsew** [comment]
> > I just removed all the package fwupd,
> 
> @ayelsew How did you remove `fwupd` without breaking your dependency tree? E.g. this happens by default if someone attempts to remove `fwupd` on Pop!_OS:
> 
> ```
> jacob@serw12:~$ sudo apt remove fwupd
> [sudo] password for jacob: 
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  pop-desktop : Depends: fwupd but it is not going to be installed
>                Depends: fwupdate
> E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
> ```

@jacobgkau You need to remove fwupd as dependence of pop-desktop at  `/var/lib/dpkg/status`

Lookup for `Package: pop-desktop` go to `Depends: ....` and remove the fwupd name.

So after that run: `sudo dpkg --remove libfwupdplugin5 fwupd`

Maybe in a `apt update`, will update the info inside `/var/lib/dpkg/status`. I guess the package won't be installed unless you run `apt upgrade` or a `apt -f install`

**Comment by ayelsew** [comment]
> That's very helpful to know. Maybe this is a fwupd bug at this point. (This issue was opened back on January 8th, 2021, and I'm not sure how recent you mean by "recent version" for those vendors being added.)
> 
> I do see that [fwupd/fwupd#3187](https://github.com/fwupd/fwupd/issues/3187) was closed back in 2021, and we have a `fwupd` version from within the last month in Pop!_OS right now (see https://github.com/pop-os/fwupd).

Yeah, it's a fwupd bug.

About the version ? It's really funny, because it was introduced in `1.6.2`, as you can see here https://9to5linux.com/fwupd-1-6-2-adds-a-plugin-to-check-lenovo-firmware-settings-support-for-new-hardware  and today we already have 1.9.0 release. Maybe fix it as was reported in https://github.com/fwupd/fwupd/issues/3187 isn't so important or wasn't so demanded. 
In this pull request https://github.com/fwupd/fwupd/pull/3218 @hughsie commited "100% untested."  😂😂

If I have time, I'll work on a PR to solve it.

**Comment by syedadil2k19** [comment]
> @jacobgkau, no, I didn't. But I coming with good news.
> 
> At second time I tried to handle the fastboot CLI on Ubuntu, the same error of Pop OS started to appear at Ubuntu. So I started to searching about fwupd, and I realize that it's a tool to update firmware and it has a daemon that listens to new devices attached in "fastboot mode".
> ## The cause
> 
> In a recent version of fwupd was introduced support to update firmware of some vendors like Lenovo that had bought Motorola.
> 
> So when we attache the phone Motorola (in my case G7 Play and @JeffRockatansky with G7 Plus), the fwupd daemon tries to recognize the device bootloader of this vendor by the command `getvar version-bootloader`, But that fastboot mode isn't the type supported by fwupd, because android don`t have the `version-bootloader` variable and here starts the bug.
> 
> So fwupd throw the error `failed to add device ...: failed to getvar version-bootloader: no response to read`, and it isn't unable to hangup the devices port. Now fastboot CLI of android can recognize the device in fastboot mode, but when we send command to the device, fastboot CLI wait for fwupd hangup to do it, but never happen. ("freezing command")
> 
> More about you can look here: [fwupd/fwupd#3187](https://github.com/fwupd/fwupd/issues/3187)
> ## Solution (my solution)
> 
> I just removed all the package fwupd, but I really removed, not disable like they said in the issue [fwupd/fwupd#3187](https://github.com/fwupd/fwupd/issues/3187)
> 
> Probably a downgrade to a version that don't add those vendors could solve too.
> 
> Now any version of fastboot CLI is working in Ubuntu and Pop OS!

**Comment by hughsie** [comment]
You could also just disable the flashrom plugin in daemon.conf too... Although testing the **latest** release and filing a bug upstream with details on how to reproduce would be better still.
