### ISSUE TITLE
Show desktop shortcut does not exist

### ISSUE THREAD

**Issue by bihellzin** [pop-os/pop#1485]
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

Show Desktop shortcut does not exist to enable. 

**Steps to reproduce:**
Go to Settings > Keyboard > Customize Shortcuts and you may not find the Show desktop shortcut.

![bug](https://i.imgur.com/rDGTyl6.png)  
  
  
  
**Expected behavior:**
Show desktop shortcut being disabled, since the official [site](https://support.system76.com/articles/pop-keyboard-shortcuts#operating-system) says it exist.

**Comment by jacobgkau** [comment]
I think the shortcut you're looking for is called `Hide all normal windows`, if you want to set it manually:

![show-desktop](https://user-images.githubusercontent.com/7199422/105069182-d6042480-5a3e-11eb-9e78-97ae99d90a96.png)

The documentation section you linked is under `Pop!_OS (up to 19.10 release) Shortcuts`, so it would not apply to 20.04 LTS or 20.10. (That older section can probably be removed at some point, since 20.04 LTS and 20.10 are the currently-supported releases.)

**Comment by bihellzin** [comment]
It worked, thanks.

**Comment by Cima9642** [comment]
Hello , it seems like this is still an ongoing issue

<img width="706" height="364" alt="Image" src="https://github.com/user-attachments/assets/b8b3241b-4163-4a0f-bb20-e7310c68db58" />
