### ISSUE TITLE
Snap aren't added to App list after install

### ISSUE THREAD

**Issue by arkhenstone** [pop-os/pop#149]
**Reporter info**

```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

```

**Issue/Bug Description**
Snap installed programs are not in application menu after install. Tried Spotify and VSCode snap, either on terminal or Software. When you run them, icons are very poor quality too.

**Steps to reproduce (if you know)**
Just install snaps.

**Expected behavior**
Application to be added in menu

**Other Notes**
Reboot seems to works.

(Discord in picture below is .deb from site, worked okay)

![image](https://user-images.githubusercontent.com/17592744/37229547-90c1730c-23e4-11e8-97d8-ba06f311ac07.png)

**Comment by brs17** [comment]
I haven't played around too much with Snaps, @ahoneybun or @isantop do either of you two have an idea?

**Comment by brs17** [comment]
@arkhenstone Thank you for submitting this issue. 

After doing some digging, it seems like the .desktop file for snaps is not copied to the necessary place on the host machine. (because snaps shouldn't have to interact much with the host machine, right?!). Looks like some configuration with the .desktop can get the icon to appear: https://askubuntu.com/questions/824248/how-do-i-use-a-desktop-file-with-a-snap-project

I believe the issue with poor quality icons is an issue with that specific package.

Let us know if this fix works for you and I'll close this issue.

**Comment by arkhenstone** [comment]
After reboot, eveything goes well. It's just the initial install that works not as expected. I suppose it doesn't change the .desktop. In ubuntu, it works well, from the app center. On the same app center, it doesn't work with pop OS. It's not package specific as I installed vscode and spotify, and both behave like that.

**Comment by brs17** [comment]
Glad everything is going well. For what it's worth Ubuntu's app store integrates snaps in ways that Pop!_Shop and elementary's Appcenter do not.
