### ISSUE TITLE
Codelite stucks in middle

### ISSUE THREAD

**Issue by jobins1492** [pop-os/pop#1497]
**Distribution (run `cat /etc/os-release`):**pop_os 20.10
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):*$Codelite*

**Issue/Bug Description:*It gets stuck in the middle of writing codes or working with it. It was not present in Linux mint or any other OS but only in this OS. After getting stuck, I need to press the left button in my mouse on its window to continue working on it.*

**Steps to reproduce (if you know):*Open Codelite14.0.0, Write some Cpp or any code. In between the program will hang or get stuck*

**Expected behavior:*The program gets stuck and it will continue only if you press the mouse's left button on anywhere in the window*

**Other Notes:*This is disappointing and affecting my work.*

**Comment by bflanagin** [comment]
@jobins1492 this issue does sound annoying, unfortunately System76 and Pop!_OS has nothing to do with CodeLite or its interactions with the system. Please file an issue with the codelite developers know [here](https://forums.codelite.org/) or on their github page. Be sure to let them know what OS you are using so that they can contact us with more in depth info.
