### ISSUE TITLE
Nvidia X server settings problem

### ISSUE THREAD

**Issue by HuangLinBao** [pop-os/pop#1508]
**Distribution: Pop!_OS 20.10:**
 
 
 
**Related Application and/or Package Version: Nvidia X server settings:**

**Issue/Bug Description:**
Can't find the choices: X server Display Configurations and X server information to configure

**Steps to reproduce (if you know):**
Switch to Nvidia graphics mode or Hybrid graphics mode

**Expected behavior:**
being able to configure displays using Xserver settings

**Other Notes:**
A picture to describe the problem:
![image](https://user-images.githubusercontent.com/57255961/105733170-aa0b0680-5f4a-11eb-9a8f-84758668282a.png)

**Comment by bflanagin** [comment]
Curious, I have a Gazelle and when I switch from Hybrid to Nvidia (and reboot) I get the option that you seem to be missing. 

See Image:

![Screenshot from 2021-01-25 10-46-38](https://user-images.githubusercontent.com/10382037/105736679-aea7ce80-5efa-11eb-95ab-e0e54921c7e3.png)

I can confirm it doesn't appear in Hybrid mode, however this is by design and nothing to be concerned with. On the other hand, if you don't see the option after rebooting and verifying you are running in Nvidia Graphics mode there could be an issue. If you could provide the nvidia driver version currently installed maybe it will shed light on the issue further,

**Comment by TaHunKwai** [comment]
Alright....it worked somehow when switching to Nvidia mode....I don't know exactly nvidia driver version  you need..and one more thing is that I am struggling with an overscanning issue with the second monitor that can't be disabled within the monitor itself..and when I opened the X server settings it showed the message of PRIME Displays cannot be controlled by Nvidia settings...How can I do it with Randr?

**Comment by bflanagin** [comment]
> I don't know exactly nvidia driver version you need.
Don't worry about it, we only need it if switching it out of Hybrid mode didn't change what you saw in the Settings-Manager.

> I am struggling with an overscanning issue with the second monitor that can't be disabled within the monitor itself..and when I opened the X server settings it showed the message of PRIME Displays cannot be controlled by Nvidia settings...How can I do it with Randr?
So unfortunately this is one of those problems that doesn't have a straight forward answer. The link below might help.
https://askubuntu.com/questions/508358/overscanning-picture-problem-using-hdmi-with-intel-graphics
