### ISSUE TITLE
Unable to Boot Into Pop OS from Windows 10 dual boot

### ISSUE THREAD

**Issue by evilthreads669966** [pop-os/pop#1540]
**Distribution (run `cat /etc/os-release`):**
pop os 20.10
Wndows 10 pro
Gazelle 15" 2020

**Issue/Bug Description:**
- I had pop os factory installed to an nvme SSD 250 GB
- I then installed a second nvme SSD 1TB same model as the factory ssd
- I disabled fast boot in Windows power options
- When I installed I just held down F7 and chose the usb key. Then installed straight to the second drive.
- Now I am unable to hold F7 down anymore to select the linux drive.
- Spacebar doesn't work either

**Comment by evilthreads669966** [comment]
I guess I'll just play planetside 2 after I get off work until I hear back from the greatest tech support in history. Sorry. I've been in my IDE for like 5-6 years. Casually coming back into the I.T. world..

**Comment by bflanagin** [comment]
Thanks for the complement @evilthreads669966. However, this issue is deep in the realm of support and isn't something we cover on our github repos. (Git-hub is primarily for bugs and feature requests)

Sense you are on System76 hardware you can get a hold of support by going to here: http://support.system76.com/ They have dealt with issues like this and I'm sure they can get you back up and running.
