### ISSUE TITLE
Should Pop!_OS advertise itself as pop?

### ISSUE THREAD

**Issue by strycore** [pop-os/pop#1561]
Having the distribution ID set to `pop` in /etc/os-release breaks software that only support Ubuntu such as Salt stack or the AMD GPU Pro driver. One could say that said software should parse the `ID_LIKE` field in the same file but sadly, I've found this is rarely the case.

Is there a reason having Pop advertise itself as `pop` in this file? This is the first thing I change on a new install because I provision my machines with Salt and I've noticed no bad side effect in changing it to `ubuntu`.

**Comment by jacobgkau** [comment]
> One could say that said software should parse the `ID_LIKE` field in the same file but sadly, I've found this is rarely the case.

If software is hard-coding distribution IDs (not the best practice in the first place) and also not checking `ID_LIKE` (which is a [standard](https://www.freedesktop.org/software/systemd/man/os-release.html) specifically for software that wants to hard-code distribution IDs without running into this problem), that needs to be fixed in the software.

Pop!_OS is its own distribution with enough differences from vanilla Ubuntu to justify not "advertising" itself as Ubuntu. The most obvious example is that Pop often ships a newer kernel than Ubuntu (it was shipping 5.8.0 on both 20.10 and 20.04 months before Ubuntu 20.04's HWE stack got 5.8.0 as an option.) It's also liable to have different versions (sometimes newer, but also subject to Pop-specific QA) of mesa, systemd, GNOME Shell, GDM, flatpak, and other components.

Since not only the user-facing GUI components but also the underlying system components can vary significantly from Ubuntu, it would not be logical to use an ID of `ubuntu`. If there's software that truly does require Ubuntu and only Ubuntu, then it may not work on Pop!_OS due to one or more of those differences. (Take the AMDGPU-PRO driver you mentioned, for example-- the installer doesn't run with an ID of `pop`, but even if you change the ID to `ubuntu`, it still won't work right now because of the kernel version.) If software checking for `ubuntu` does work on Pop, then `pop` should be added to the software's checks or (even better) the software should use `ID_LIKE` instead (or in addition.)

Regarding Salt, it looks like there's already an open issue in their repo for using `ID_LIKE`: https://github.com/saltstack/salt/issues/59061 I also found a recently-merged PR which looks like it was supposed to add `pop` to the list of `ID`s: https://github.com/saltstack/salt/pull/58443

**Comment by strycore** [comment]
Thanks, that makes sense. I hadn't looked at the Salt open tickets for a few months but it now looks it's taking the right direction.
