### ISSUE TITLE
No internet after Reboot

### ISSUE THREAD

**Issue by TomCooper01** [pop-os/pop#1566]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
No related applications triggered.

**Issue/Bug Description:**
When a reboot occures the network connection is disabled, not able to ping the local network and doesn't come back up after following the network troubleshooting steps, only current fix is a refresh install, this effects both the wifi and ethernet

**Steps to reproduce (if you know):**
Reboot the system, from install.

**Expected behavior:**
No network connection wireless or ethernet.

**Other Notes:**
https://www.reddit.com/r/pop_os/comments/jgzpn4/no_internet_after_updating_to_2010/

**Comment by bflanagin** [comment]
@TomCooper01; Thanks for putting in the issue, but I think you cut yourself off during the bug description. Also I'm reading through the reddit thread for more context. Is your experience that the upgrade from 20.04 is causing the issue? I haven't personally seen this problem, but there might be something to the firewalld / UFW issue that others brought up. If you can, attach the output of `dpkg -l` (from and affected machine) to this thread I can try to recreate the issue here so we can better diagnose the issue.

```
dpkg -l > TomCooper01.txt

```
You don't have to name it "TomCooper01" but it will make it easier for me if its uniquely named.

**Comment by TomCooper01** [comment]
[TomCooper01.txt](https://github.com/pop-os/pop/files/6078192/TomCooper01.txt)

@bflanagin I cut off I was going to say that it didn't work with either wifi and ethernet.

**Comment by bflanagin** [comment]
Great! Thanks for the file. I was able to use the list to create a VM with the same packages installed (to see if its the packages that cause an issue.)  So that I know I'm following the issue and pattern of events that lead to your issue here is what I did:

1. Installed Pop!_OS 20.04
2. Ran updates
3. Installed all the applications listed in the file you supplied
4. Rebooted system
5. Turned on the firewall application set to "Home"
6. Ran  `pop-upgrade release upgrade`
7. Rebooted machine when prompted and allowed upgrade to do its thing.
8. Logged in and checked internet connection.

Everything worked on my end without issue, could there be something you configured after the install, but before the upgrade that might be at play? Did my steps mimic your actions that caused the issue?

**Comment by TomCooper01** [comment]
@bflanagin I have restarted my system, I have no internet connection after the reboot. 
I didn’t change anything but mine didn’t allow me to gain internet connection after the first reboot. Could I send you anything more to help?

**Comment by TomCooper01** [comment]
Found issue. I completely forgot I had changed the DNS to use 1.1.1.1 as my ISPs DNS server is always slow. I changed it and the internet has come back.

**Comment by TomCooper01** [comment]
@bflanagin Thanks so much for the help troubleshooting!

**Comment by bflanagin** [comment]
lol, glad to hear it!  I'll go ahead and close the ticket.
