### ISSUE TITLE
Backlight Control not working on Thinkpad X1 Titanium Yoga

### ISSUE THREAD

**Issue by simonheb** [pop-os/pop#1667]
I am running a fresh installation of Pop!_OS 20.10 and did a dist-upgrade. The only additional kernel option I added was `nomodeset`

**Issue/Bug Description:**
Screen backlight control keys are not working. Brightness also not responsive to xrandr.

**Steps to reproduce (if you know):**
Pressing the brightness up/down button.

**Expected behavior:**
Screen becoming brighter/dimmer

**Other Notes:**
Relevant Hardware is:
 - Display: 13.5" QHD (2256x1504) IPS 450nits, AR / AS, 72% NTSC, Touch
 - Graphics: Integrated Intel® Iris® Xe

I am documenting all progress/issues with running Pop!_OS on aThinkpad X1 Tiatium Yoga here: https://www.reddit.com/r/pop_os/comments/mxl4gd/pop_os_support_for_thinkpad_x1_titanium_yoga_tldr/

**Comment by ids1024** [comment]
Gnome-settings-daemon uses only one backlight device, ignoring any others (probably not the best design; not sure how non-Gnome systems tend to do this). On some laptops it ends up choosing a "backlight" that doesn't seem to have any effect rather than the correct driver.

The `light` command (`apt install light`) seems to work on some hardware. Alternately, the laptop may perhaps not have a Linux kernel driver.

**Comment by simonheb** [comment]
the problem was the graphics driver. the 5.12 kernel does not have it. there are patches available, and here I wrote down how to apply the patches: https://gist.github.com/simonheb/b54b91358c3d7e2960a4f6e13e95ac54
