### ISSUE TITLE
Pop OS 20.10 showing severe graphical glitches in Flatpak Programs

### ISSUE THREAD

**Issue by BalooRJ1** [pop-os/pop#1704]
**Distribution (run `cat /etc/os-release`):** Pop! OS 20.10
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** Some Flatpak Repo packages, including Jitsi Meeting, Signal, and Protonmail Bridge.

**Issue/Bug Description:** Many severe graphical glitches ONLY in flatpak programs. See screenshot here: https://imgur.com/Ya5a1z6.png

**Steps to reproduce (if you know):** Simply opening the program and moving cursor around within program shows graphical glitches. 

**Expected behavior:** Discolored squares should not appear.

**Other Notes:** Happens across multiple Flatpak programs, not just one.

**Comment by maxi-k** [comment]
I have the same issue (see [https://imgur.com/VAiOtnl](spotify), cropped for privacy) after updating using PopShop.

I fixed it temporarily on my system by removing the freedesktop GL flatpak:
```
flatpak remove org.freedesktop.Platform.GL.default
```
This fixed it in all flatpak apps I have installed, though I had to switch to the `deb` version of zoom because it depended on it.

**Comment by bflanagin** [comment]
Thanks for the help @maxi-k! 
@BalooRJ1, we've seen some other reports about GL issues with flatpak. Though the issue is primarily upstream ,and thus out of our control, getting more information about your system might help us help the flatpak developers find a solution. Mind sharing your hardware stats?

**Comment by BalooRJ1** [comment]
Sure thing thank you @bflanagin!

Here is my hardware:

CPU: Ryzen 5 3600X 6-core processor
GPU: Powercolor Radeon RX 5600XT
RAM: 16GBx2=32GB total
Motherboard: ASUS ROG Crosshair VIII Impact
Hard Drive: WD 500GB NVme SSD

**Comment by maxi-k** [comment]
Thanks, @bflanagin!

My system is very similar, maybe this helps narrow it down:

- CPU:  Ryzen 5 3600XT
- GPU: XFX Radeon RX 5600 XT PRO THICC III (6GB)
- Motherboard: MSI X570-A Pro

**Comment by lionirdeadman** [comment]
This was a mesa bug with Mesa 20.0.3, a patch was backported and it has been published. `flatpak update` should fix it.

**Comment by bflanagin** [comment]
Thanks for the link @lionirdeadman. I'm going to close the ticket.
