### ISSUE TITLE
Tap to click Touchpad gesture in lockscreen not working

### ISSUE THREAD

**Issue by Shubham20091999** [pop-os/pop#1709]
I installed Pop OS in my laptop, I use gestures to navigate as buttons on the touch pad are not working, but these gestures like tap to click are not working on the lockscreen.

**Comment by bflanagin** [comment]
@Shubham20091999 would you mind giving a little more information about your problem? If you could follow this template we will be able to diagnose the issue further.

**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**



**Issue/Bug Description:**



**Steps to reproduce (if you know):**



**Expected behavior:**



**Other Notes:**

**Comment by Shubham20091999** [comment]
Distribution:
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

Issue/Bug Description:
Cannot use touchpad gestures(eg Tap to Click) in Login Screen. I am not able to use touchpad gestures(like tap to click) to shutdown or restart the system the system

Steps to reproduce:
In a laptop, Restart Pop OS then in login screen,touchpad gestures are not working.

Expected behavior:
Touchpad gestures should work as i have turned it on in the settings

Other Notes:
I think same problem of touchpad gestures not working happens when installing Pop OS.

**Comment by leviport** [comment]
I believe this is just default behavior for GDM3, and it's certainly not specific to Pop!\_OS. There is some discussion here about how to enable the setting: https://unix.stackexchange.com/questions/266586/gdm-how-to-enable-touchpad-tap-to-click. Even though it looks like they're on Arch, I'd imagine the same fix would work on Pop.
