### ISSUE TITLE
Kernel Limitations for Docker - Your kernel does not support - Please add support

### ISSUE THREAD

**Issue by wellington1993** [pop-os/pop#1718]
**Distribution (run `cat /etc/os-release`):**
```ini
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Pop!_OS 20.10"
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
*dockerd*

**Issue/Bug Description:**

When I run: `sudo service docker status`

I see that warnings:
```c
mai 30 15:26:36 pop-os dockerd[5969]: time="2021-05-30T15:26:36.332729186-03:00" level=warning msg="Your kernel does not support CPU realtime scheduler"
mai 30 15:26:36 pop-os dockerd[5969]: time="2021-05-30T15:26:36.332761427-03:00" level=warning msg="Your kernel does not support cgroup blkio weight"
mai 30 15:26:36 pop-os dockerd[5969]: time="2021-05-30T15:26:36.332772098-03:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
mai 30 15:26:36 pop-os dockerd[5969]: time="2021-05-30T15:26:36.333660598-03:00" level=info msg="Loading containers: start."
mai 30 15:26:36 pop-os dockerd[5969]: time="2021-05-30T15:26:36.566796287-03:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16.>
```
- Your kernel does not support CPU realtime scheduler
- Your kernel does not support cgroup blkio weight
- Your kernel does not support cgroup blkio weight_device

**Steps to reproduce (if you know):**

**Expected behavior:**
PopOS kernel support for that things cited. 

**Other Notes:**

**Comment by bflanagin** [comment]
Currently Pop!_OS uses upstream kernel images provided by Ubuntu which are designed for general use. Looking into the errors listed the addition of these options may cause instability on some systems which is why they are disabled by default. We may look into this at a later date, but for now the defaults will remain. 

If you are still interested in enabling these features here are a few resources I have found that might help you. 

Stack Overflow: https://stackoverflow.com/questions/46563332/docker-daemon-container-real-time-scheduling-with-ubuntu-linux-host

Docker Docs: https://forums.docker.com/t/issues-with-sudo-systemctl-status-docker/98564
