### ISSUE TITLE
Menu buttons in dock not working

### ISSUE THREAD

**Issue by AyhamAl-Ali** [pop-os/pop#1804]
Just straight into the issue,

After updating I thought it will only make things better but not! after waiting for around 2 hours updating I opened my PC and found all my extensions gone which is the most thing that annoyed me!

The `super` button doesn't show the Launcher
All the new buttons in the new dock are not working (apps, workspaces, launcher) This just ruined my day. Sad to see this happens to Pop OS after using it for around a year.

**Comment by jacobgkau** [comment]
Extensions being deactivated is expected behavior, see https://github.com/pop-os/upgrade/pull/176. One of the screens in the initial setup wizard explained that you can reinstall extensions from extensions.gnome.org (recommended) or restore them from the backup directory at `~/.local/share/gnome-shell/extensions.bak/`.

For the other issues, more information would be needed to understand what's going on:

- Please provide a screenshot of the settings currently set in Settings -> Desktop.
- Does `Super + /` open the launcher, if just `Super` doesn't?
- Do you see the Pop Shell drop-down menu near the top right of the screen? (This is the menu with `Tile Windows` as the first option.)
- Please provide the output of `sudo journalctl --follow` while clicking the three buttons in the dock that don't work so we can see if any errors are being logged.
- Please run `apt list --installed > packages.txt` and attach the text file to a message so we can see what packages you have installed, and provide any other information about configuration that you've performed (e.g. GNOME Tweaks settings, other installed extensions, etc.)
- Please provide information about what hardware you are using. Is this a System76 computer or is it third-party hardware?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by mmstick** [comment]
Extensions are removed by default because they often cause an inability to log into your session after a major version GNOME Shell upgrade.

**Comment by AyhamAl-Ali** [comment]
Thank you for quick answer, after seeing the back up folder I am much less annoyed right now. I just didn't like the idea of removing them without any confirmation because I made a lot of changes to my Desktop Environment and it would be a big problem if everything is just gone.

**01** 
![image](https://user-images.githubusercontent.com/20037329/124951245-d6f43700-e01b-11eb-8956-22e28d4990f7.png)

**02** As for `Super + /` it doesn't work, `Super` shows the workspaces when clicked.
03 No

**04** 
```
Jul 08 18:40:02 ayham-pop dbus-daemon[1705]: [session uid=1000 pid=1705] Successfully activated service 'org.freedesktop.Tracker1'
Jul 08 18:40:02 ayham-pop systemd[1294]: Started Tracker metadata database store and lookup manager.
Jul 08 18:40:02 ayham-pop zeitgeist-datah[4638]: zeitgeist-datahub.vala:210: Error during inserting events: GDBus.Error:org.gnome.zeitgeist.EngineError.InvalidArgument: Incomplete event: interpretation, manifestation and actor are required
Jul 08 18:40:12 ayham-pop zeitgeist-datah[4638]: zeitgeist-datahub.vala:210: Error during inserting events: GDBus.Error:org.gnome.zeitgeist.EngineError.InvalidArgument: Incomplete event: interpretation, manifestation and actor are required
Jul 08 18:40:12 ayham-pop systemd[1294]: Started Application launched by gnome-shell.
Jul 08 18:40:12 ayham-pop systemd[1294]: app-gnome-pop\x2dcosmic\x2dapplications-20561.scope: Succeeded.
Jul 08 18:40:13 ayham-pop zeitgeist-datah[4638]: zeitgeist-datahub.vala:210: Error during inserting events: GDBus.Error:org.gnome.zeitgeist.EngineError.InvalidArgument: Incomplete event: interpretation, manifestation and actor are required
Jul 08 18:40:13 ayham-pop systemd[1294]: Started Application launched by gnome-shell.
Jul 08 18:40:13 ayham-pop systemd[1294]: app-gnome-pop\x2dcosmic\x2dworkspaces-20566.scope: Succeeded.
Jul 08 18:40:14 ayham-pop zeitgeist-datah[4638]: zeitgeist-datahub.vala:210: Error during inserting events: GDBus.Error:org.gnome.zeitgeist.EngineError.InvalidArgument: Incomplete event: interpretation, manifestation and actor are required
Jul 08 18:40:14 ayham-pop systemd[1294]: Started Application launched by gnome-shell.
Jul 08 18:40:14 ayham-pop systemd[1294]: app-gnome-pop\x2dcosmic\x2dlauncher-20572.scope: Succeeded.
```

**05** https://pastebin.com/a5nLjcUH

**06** 
![image](https://user-images.githubusercontent.com/20037329/124951680-3c482800-e01c-11eb-8ea6-eb2290bf5994.png)

**Comment by jacobgkau** [comment]
It sounds like neither COSMIC nor Pop Shell are actually starting. If you create a new user account and log into it, do the Super key and the top-right Pop Shell menu work?

**Comment by AyhamAl-Ali** [comment]
My system is acting weird at the moment, I created a system user but nothing is showing in my gdm even tho I restarted it and nvidia drivers are broken I think everytime I switch to another tty all windows start to show black screens

**Comment by AyhamAl-Ali** [comment]
I created it using `useradd` I will do it the way you told me now

**Comment by AyhamAl-Ali** [comment]
Indeed, the buttons do work in the new user

**Comment by jacobgkau** [comment]
> I ran `sudo gnome-control-center` and it worked

You generally shouldn't run gnome-control-center as the root user. Clicking the `Unlock` button shown in the top right of your screenshot should allow your normal (administrative) user to add/remove users. Is the button clickable if you switch back to one of the default Pop!_OS themes?

> Indeed, the buttons do work in the new user

This means the issue is being caused by something in your primary user's configuration. I would recommend disabling any third-party extensions that you've re-enabled, setting your themes back to default, etc. until the buttons start working again. That way, you can narrow down exactly what's causing the buttons to no longer work. If it's a conflict with a particular extension or setting, that's something we can look into closer.

A potentially quicker method would be moving your entire `.local`, `.config`, and `.cache` directories to another location (like a backup directory) and logging out/in, to eliminate a lot of the configuration at once. If you move all of your config files out of the way and the issue is still occurring, then it could be something else like a gsetting.

**Comment by AyhamAl-Ali** [comment]
Thank you for all the help you're giving, I think it is something related to my extensions because I have a lot, I will start debugging and see what caused it and let you know.

**Comment by AyhamAl-Ali** [comment]
All seems to work now, I have disable multiple extensions but I don't think it is due to that, simply the `pop cosmic` extension was off :thinking: all seems to work perfectly now. Thanks a lot.
