### ISSUE TITLE
[18.04] Do Not Disturb Switch widget has different background

### ISSUE THREAD

**Issue by sramkrishna** [pop-os/pop#185]
If I access the message center via Meta-M, the "Do Not Disturb" widget has a darker background then if I clicked on the Date.

Shows up in current testing ISO rev 2.

**Comment by sramkrishna** [comment]
The problem is a default focus it seems.  It probably could be fixed if you set the widget not to receive focus  perhaps.

**Comment by kylecorry31** [comment]
I made it so it can no longer receive focus, is that what you want? 

https://github.com/kylecorry31/gnome-shell-extension-do-not-disturb/commit/709237a223ad1d61deb867a8f406a4e851ae055b

**Comment by jackpot51** [comment]
I think that does it @kylecorry31 !

**Comment by brs17** [comment]
We were discussing on mattermost, that we think we do want the ability for the toggle to receive focus. It also looks a lot less bad with the new theming. So we aren't quite sure that is the fix we want.

**Comment by brs17** [comment]
Conversation from mattermost:

kyle31
10:39
@sri I fixed that focus issue for the do not disturb toggle by making it unable to receive focus, is that what you wanted? https://github.com/kylecorry31/gnome-shell-extension-do-not-disturb/commit/709237a223ad1d61deb867a8f406a4e851ae055b

shpurk
10:40
I'm not sure it was not wanting it to be able to focus, I think it was more that super+m was by default focusing on dnd

sri
10:40
@kyle31 right, if you set the widget to doesn't receive focus,  that should fix the issue - so your change looks correct to me.
10:40
but we should test it.
10:40
  

kyle31
10:40
It does fix that super+m issue, but it makes it so you can't tab to it which may not be what you want
sri
10:41
then we probably want to find a way as shpurk says to not have the default focus on that widget.

shpurk
10:41
yeah, I'd think it should still be an option to receive focus, no?

sri
10:41
which would mean that when the message center is activated one of the widgets should get the focus.

kyle31
10:42
  Actually, I just checked and it does allow you to tab to it but it just doesn't become off-colored
10:44
 
The reason why it gets default focus when doing super+m is because it is on the left side and if there are no notifications it will be the first item in the menu, thus receiving focus by default. Not sure if there is a way around this other than it not being focusable (you can still hit enter right after doing super+m to toggle the switch, it just doesn't visually appear focused)

shpurk
10:47
@kyle31 @sri I'm thinking I want to take another look at that dnd highlighting (hopefully this afternoon). I'm curious if with the new theme it doesn't look as bad and maybe is just good as is

kyle31
10:47
Sounds good, I can always revert the commit if you choose to keep it as is

shpurk
10:48
Did you push the changes?
10:48
on your repo(upstream) you did

sri
10:52
I would probably branch and then push your changes to that branch.

shpurk
11:03
@kyle31 @sri and I just looked at what it looks like in the new theme, definitely looks a lot better. But of course the question is raised of how it looks in different themes

**Comment by brs17** [comment]
I think after further discussion we want to revert back to the way it was (where it is highlighted). This isn't a bug at all.
