### ISSUE TITLE
Microsoft Pro IntelliMouse pastes twice with middle-click macro

### ISSUE THREAD

**Issue by DavidSmolinski** [pop-os/pop#1851]
**Distribution (run `cat /etc/os-release`):**
VERSION="21.04"
VERSION_CODENAME=hirsute

**Issue/Bug Description:**
**Steps to reproduce (if you know):**

1. In Windows 7, assign paste (ctrl v) to the wheel button on a Microsoft Pro IntelliMouse.
2. In Pop!_OS, copy "paste" and paste with that mouse's wheel button.
3. It pastes "pastepaste" instead of "paste".

**Expected behavior:**

The mouse should paste once. It used to work on Pop!_OS.

**Comment by jacobgkau** [comment]
Just from the description, it sounds like what's happening is this:

- Middle-click is pasting the selection clipboard (this is a default behavior in Linux.)
- Your additional macro is sending Ctrl-V, which is pasting the copy clipboard.

Try doing the following:

1. Install GNOME Tweaks (`sudo apt install gnome-tweaks`)
2. Launch GNOME Tweaks (`gnome-tweaks`)
3. Navigate to the `Keyboard & Mouse` page and disable the `Middle Click Paste` setting.

Now, you should only see one paste, from the Ctrl-V action. Does this work? (If so, I'm not sure there's anything actionable to be done for this, since middle-click and Ctrl-V are both sane default actions on their own.)

**Comment by jacobgkau** [comment]
I'm closing this issue since we haven't heard back in over a week and it sounds like everything is working as designed. If you want the middle mouse button to send a keyboard macro for all of your operating systems, then you should disable mouse button 3 or disable middle mouse pasting within Pop!_OS.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).
