### ISSUE TITLE
Legacy BIOS Installation, GRUB incorrectly labels Pop!_OS

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#188]
**Distribution - (run ```cat /etc/os-release```)**
 Pop!_OS 18.04 debug release#9

**Issue/Bug Description**
With a machine (lemu8) set in legacy BIOS mode, the GRUB menu appears and refers to the Pop!_OS install as "Ubuntu". 

**Expected behavior**
GRUB should have the entry "Pop!_OS".

**Other Notes**
#28 Partly discusses this issue back in 17.10.

**Comment by cassidyjames** [comment]
I'm still seeing this today on the latest test ISO

**Comment by vchakravorty** [comment]
This can be fixed by modifying the value of the `GRUB_DISTRIBUTOR` switch in `/etc/default/grub` to `lsb_release -d -s 2> /dev/null || echo Pop!_OS`
<img width="334" alt="grub_default" src="https://user-images.githubusercontent.com/6874518/49866315-6cf85e80-fe2d-11e8-82df-f305142630aa.PNG">

Run `sudo update-grub` and reboot your system. You should see:
<img width="309" alt="grub_list" src="https://user-images.githubusercontent.com/6874518/49866487-eb550080-fe2d-11e8-9956-2dfe77d1bbc2.PNG">

**Comment by laubster** [comment]
(Testing shows that the originally supplied `lsb_release -i -s` command returns an initcapped value for the ID value in `/etc/os-release` .) The bug as reported by brs17 is still present in 19.10, and vchakravorty's workaround does still function, but IMO the distributed code should reflect vchakravorty's version so users don't need to intervene. Having grub display "Ubuntu" or "Debian" just seems wrong.

**Comment by brs17** [comment]
This will be resolved with the release of Pop!_OS 20.04.

**Comment by QEDeD** [comment]
@brs17 was the issue resolved?

**Comment by leviport** [comment]
It has! Here's what it looks like after a clean 20.04 install.
![PXL_20210513_164332280](https://user-images.githubusercontent.com/13512097/118158593-3b5a9780-b3d9-11eb-8d0a-cdc71fd5bdb4.jpg)
