### ISSUE TITLE
The system just freeze when i change from external keyboard to integrated keyboard.

### ISSUE THREAD

**Issue by Guztaver** [pop-os/pop#1897]
**Distribution:** Pop!_OS 21.04 , CodeName "Hirsute"

**Issue/Bug Description:**  When i using the system, in the browser or the system, and i change to my laptop keyboard, the system freeze for 3 seconds, and returns. That's happens straight, and is frustrating!

**Steps to reproduce:**  Press a Key in one of keyboards, and press in other

**Expected behavior:** Don't lag, like in others system's, examples: Ubuntu, Arch Linux, Fedora, Debian, [...]

**Comment by leviport** [comment]
I believe I've seen what you're describing, but if it's what I think it is, I could only make it happen if I was trying to type on two separate keyboards at the same time (with one hand on each keyboard). How quickly are you changing between the two different keyboards? Are you unplugging the external keyboard, or just starting to type on the built-in keyboard?

> Don't lag, like in others system's, examples: Ubuntu, Arch Linux, Fedora, Debian, [...]

Could you clarify this a bit? Last time I investigated this behavior, I could reliably reproduce it on Ubuntu and Manjaro, which is why I stopped investigating. Are you saying the distros you listed do not have the same behavior?

**Comment by Guztaver** [comment]
Hi leviport,

>  How quickly are you changing between the two different keyboards? 

The time of switch, is any time, can be a minute, can be a hour, is in any time.

> Are you unplugging the external keyboard, or just starting to type on the built-in keyboard?

I just start to type, and the entire system freeze, audio, video, everything

> Are you saying the distros you listed do not have the same behavior?

Yep, I don't have this problem in any other distro, just in PopOS

**Comment by leviport** [comment]
Ah I see. I don't think it's related to the behavior I described in my last post then. Can you give me the brand and model of the keyboard and the laptop you're using?

**Comment by Guztaver** [comment]
> Can you give me the brand and model of the keyboard and the laptop you're using?

The keyboard is a conventional keyboard, with ABNT2 model, and the laptop is an LGS43, an i3 2330M w/ HD Graphics 3000, 640GB of HDD, and 6GB of RAM.

Don't are a bad PC :/
