### ISSUE TITLE
Installer button reads Erase when set to preseve home partition, does not confirm changes

### ISSUE THREAD

**Issue by dwangoac** [pop-os/pop#198]
**Distribution:**
`Pop!_OS 18.04 LTS (Testing)`
 
**Steps:**
During installation, specify an existing partition to use as the home partition with the format option disabled and attempt to proceed through the installation.

**Result:**
The button to continue with the process starts with the word "Erase". If the button is pressed there is no confirmation or review screen to allow the user to confirm the changes.

**Expected:**
Because the home partition is explicitly set to not be formatted, the button to continue the installation should not read "Erase". The button should instead consist of a "Review Changes" or similarly named button which displays a pop-up confirmation dialog showing the proposed partition changes and allowing the user to Continue or Cancel.

**Additional information:**
I confess I've forgotten what the rest of the button reads but I believe it's "Erase & Continue" or similar. The above expected behavior is based on existing partitioning tools in OS installers and is a critical step in ensuring hapless users (or even well-seasoned ones) do not make fatal mistakes.

**Comment by cassidyjames** [comment]
Thanks for reporting this @dwangoac! It looks like you have a couple of points here:

1. The final destructive action says "Erase" when you are preserving home, and
2. There is not a "Review Changes" step.

For point 1, I agree that it can be a little confusing when preserving home, but it's very important to understand that other data on your machine is being erased; i.e., whichever partition is set to hold your root. Because of that, I would not be comfortable removing the word "Erase" here. But perhaps there could be clearer copy on this page about what is going to happen?

For point 2, we explicitly designed the installer to not have a review step. In the vast majority of cases, this adds an arbitrary step that artificially slows down the user to show them information they _just_ saw one or two steps ago. Instead, we rely on making sure there are explicit user actions before we allow the user to begin the installation; i.e. they _must_ select a drive on which to install—even when there is only one drive—and they _must_ explicitly select the red danger "Erase and Install" button before any action is performed.

I'm not sure how to resolve your points without introducing extra complexity for the majority use case, so I'm going to close this issue for now. If you have any ideas, feel free to share! We can always re-open and revisit this issue.
