### ISSUE TITLE
Right mouse button in laptop touch-pad is not working

### ISSUE THREAD

**Issue by 20MIS7057** [pop-os/pop#1989]
Distribution (run cat /etc/os-release):

VERSION="21.04"

Issue/Bug Description:
 1. The right button on the touchpad is functioning as the left button but working fine when an external mouse is used.

**Comment by jacobgkau** [comment]
What laptop are you using and what model of touchpad does it have?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by 20MIS7057** [comment]
PC Info: 
Model:         Dell Vostro 35000 
processor:   intel i5 11th gen 
ram : 8gb 

touch pad details 
 Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ DELL0A24:00 06CB:CDD6 Mouse             	id=9	[slave  pointer  (2)]
⎜   ↳ DELL0A24:00 06CB:CDD6 Touchpad          	id=10	[slave  pointer  (2)]
⎜   ↳ PS/2 Generic Mouse                      	id=15	[slave  pointer  (2)]

**Comment by leviport** [comment]
It looks like the newer Dell Vostro 3500's use a clickpad instead of discrete buttons. By default, Pop uses 2-finger click or tap for right click on clickpads. If you wish to change that setting so that single-finger clicking the right side of the clickpad registers a right click, install `gnome-tweaks` and launch it, navigate to the "Keyboard & Mouse" section, and under "Mouse Click Emulation", change the setting from "Fingers" to "Area".
![2021-11-10_08-25](https://user-images.githubusercontent.com/13512097/141141485-1b3676c0-bbbb-4e8c-a70d-63ac0107cba2.png)
 
It may be worth noting that tap-to-click will still only right click with a two-finger tap after this setting is changed.
