### ISSUE TITLE
KDE crashed after latest update

### ISSUE THREAD

**Issue by rat-h** [pop-os/pop#2098]
I've been using Pop_OS! with KDE desktop for almost 6 years. Everything was smooth and very nice until the last update, which was installed on my Framework laptop a few days ago. Now KDE is completely broken. I reinstall Pop!_OS 20.04 LTS from scratch and [used these steps to install kde-stadard](https://support.system76.com/articles/desktop-environment). Even in a clean default installation,  KDE is broken. plasmashell constantly crashes. Almost all windows are unreadable.  That is my daily-driver, working horse, research station. My work has been completely paralyzed for the last 3 days or so. Please help, SOS! :scream: 

[Screenshots and plasmashell bug report attached to my support request on chat.pop-os.org](https://chat.pop-os.org/pop-os/pl/qg3ki5kqd78jugme1ubgzkhyre)

**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
`apt install kde-standard`

**Issue/Bug Description:**
1. plasmashell crashes
2. windows appear without any content or with broken messages/fonts/figures
3. KDE is very sluggish and any app _may_ (but may not) open window in a minute or so.

**Steps to reproduce (if you know):**
1. Install Pop!_OS 20.04 LTS
2.  sudo apt update && sudo apt upgrade -y
3. sudo apt install kde-standard
4. sudo reboot
5. login into KDE desktop

**Expected behavior:**
Normal functional KDE.

.

**Comment by jacobgkau** [comment]
> I've been using Pop_OS! with KDE desktop for almost 6 years.

That's quite impressive, considering Pop!_OS was released in October 2017, and has only been around for a little over four years. 😆

> 1. plasmashell crashes
> 2. windows appear without any content or with broken messages/fonts/figures
> 3. KDE is very sluggish and any app may (but may not) open window in a minute or so.

I am not seeing this on a System76 Gazelle 16 (gaze16-3060). I am able to log into KDE Plasma and open/use applications normally:

![Screenshot_20211221_085725](https://user-images.githubusercontent.com/7199422/146960440-ea9e38c5-2ea8-4923-a484-0162e97c5677.png)

What hardware are you using?

> sudo apt install kde-standard

When running this command, I was given the option to use `gdm3` or `sddm` as the display manager. GDM is the Pop!_OS default, so that's what should be selected. Are you using that, or SDDM? (If you chose SDDM, try switching it back with `sudo dpkg-reconfigure gdm3`.)

> That is my daily-driver, working horse, research station. My work has been completely paralyzed for the last 3 days or so.

Are you able to log into Pop!_OS's default COSMIC desktop environment? I'm a KDE user myself and can understand your preference, but that would at least allow you to use your computer in the meantime (and is important to know for troubleshooting purposes, especially since this is sounding like it might be related to hardware more than KDE.)

For a machine doing mission-critical work, I personally would not recommend relying on a non-standard/non-default desktop environment. If KDE Plasma is a must and you want something Ubuntu-based, [Kubuntu](https://kubuntu.org/) or [KDE Neon User Edition](https://neon.kde.org/) may be worth considering, unless you need the hardware enablement features of Pop!_OS.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by rat-h** [comment]
> That's quite impressive, considering Pop!_OS was released in October 2017, and has only been around for a little over four years. laughing

Oh well, I thought I switched to Pop_OS in 2015, when I bought my MacBook Pro and installed Linux instead of macOS, but I may be mistaken. Anyway, it feels like I have been using Pop_OS all my life  :smile: 

> What hardware are you using?

Framework laptop. It has worked with PoP_OS+kde since the end of September. Everything was fine until Thursday or Friday, when I hit the update button. Silly me!

> When running this command, I was given the option to use gdm3 or sddm as the display manager. GDM is the Pop!_OS default, so that's what should be selected. Are you using that, or SDDM? (If you chose SDDM, try switching it back with sudo dpkg-reconfigure gdm3.)

Yes, and I selected `gdm`. I've checked that it does the same thing with `ssdm`

>Are you able to log into Pop!_OS's default COSMIC desktop environment?

Yes, and COSMIC works fine. I just don't really know how to use it efficiently. I need to learn every small trick, which takes lots of time. 

> For a machine doing mission-critical work, I personally would not recommend relying on a non-standard/non-default desktop environment. If KDE Plasma is a must and you want something Ubuntu-based, Kubuntu or KDE Neon User Edition may be worth considering, unless you need the hardware enablement features of Pop!_OS.

I agree! Unfortunately, Kubuntu/Manjaro-KDE/Neon cannot support full-disk encryption with multiple LVM inside for root and /home partitions. Having separate partitions is critical for me because I'm dealing with pretty big data and can shoot-my-feet easily by downloading the next gigantic file for analysis and fill up a whole disk. Separate root and /home help to deal with this a lot. Full-disk encryption is the requirement of my university.


> I am not seeing this on a System76 Gazelle 16 (gaze16-3060). I am able to log into KDE Plasma and open/use applications normally

I'll record a video tonight and put a link here. I hope it isn't a hardware related problem.

**Comment by rat-h** [comment]
**Update**
I recorded the second launch of freshly installed PoP_OS with KDE. Can find it [here](https://storage.r-a-r.org/index.php/s/2XpsoQYRzdKfxbR) and another one [here](https://storage.r-a-r.org/index.php/s/yfM2m57TeG42nCQ). The problem manifested at the beginning as a window (maybe popup message, some setting from taskbar, or a regular application) does not appear on the screen, or appears as a blank white rectangle, sometimes with window decoration (topbar, close :x: button), sometimes completely blank. After 3-4 of such events, plasmashell will crash.

**However, after today `sudo apt update && sudo apt upgrade -y` and reboot, the problem is gone (seems), at least I cannot reproduce it anymore.**
