### ISSUE TITLE
Weird tap switching behavior with 3 finger gestures

### ISSUE THREAD

**Issue by ZagButNoZig** [pop-os/pop#2193]
**Distribution (run `cat /etc/os-release`):**
 
 
![image](https://user-images.githubusercontent.com/39175622/151407857-f5f4df93-90ae-40e1-840e-5f7eeecb117a.png)

**Issue/Bug Description:**
When having 3 or more windows open the 3 finger gestures to switch tabs have weird behavior. 
If I open the following windows: Firefox, Terminal, Settings. 
Firefox is in focus. This is my dock layout :
![image](https://user-images.githubusercontent.com/39175622/151408356-2a815876-cdcc-4d29-b572-cdab15c75a57.png)
Now I swipe left with 3 fingers this switches me to the terminal. 
![image](https://user-images.githubusercontent.com/39175622/151408477-1aa6aebf-12a7-4271-93d3-8b6e5da9471b.png)

If I swipe left again nothing happens. Shouldn't it switch to the settings tab?

![image](https://user-images.githubusercontent.com/39175622/151417894-b4231dfe-7a18-4512-9697-1bfed3f7854f.png)

**Steps to reproduce (if you know):**
1. Open 3 windows
2. Swipe left 

**Expected behavior:**
The second swipe left should switch to the second settings tabs.

**Other Notes:**
![image](https://user-images.githubusercontent.com/39175622/151408189-ce955395-ef8e-469a-a1a7-8f962a2d20af.png)

**Comment by leviport** [comment]
Could you clarify what you mean by tabs? Do you have those three windows stacked?

3-finger swipe is supposed to change focus in a direction, so its behavior depends on how the windows are arranged on the screen, not where they're arranged in the dock.

**Comment by ZagButNoZig** [comment]
Oups sorry, yes stacked on top of each other. I have updated the original post.

**Comment by leviport** [comment]
Ah, this is in floating mode. I was referring to the kind of stacking that can be done in tiling mode, but I think I understand what you mean now. With the arrangement in the screenshot you provided, I would expect a leftwards swipe to focus the terminal. After that, since the terminal is further to the left than the Settings window, I would not expect another leftwards swipe to change focus to Settings.

The 3-finger swipe gesture kinda makes more sense in tiling mode, but I believe it's working as expected in this case.
