### ISSUE TITLE
Weird messages regarding login keyring

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#2195]
**Distribution (run `cat /etc/os-release`):**
 
 20.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Unknown

**Issue/Bug Description:**

Some time after booting up (usually within minutes), I get a dialog coming up that says "Authentication required   The login keyring did not get unlocked when you logged into your computer".

**Steps to reproduce (if you know):**

I suspect that the culprit is autologin. If you enable autologin during installation, then the keyring never gets unlocked. Otherwise it I believe does, in the course of logging in manually. This is just a hunch on my part due to divergent code paths and the fact that this never occurred until I enabled autologin.

I suppose I should mention that autologin is considered insecure by some people, but provided that (1) you're using full-disk encryption with a strong key, (2) you're setting up a single-user system, and (3) remote login is disabled, then AKAIK it should be safe and has the advantage of saving the user from an unncessary double login. Feel free to explain why I'm wrong.

**Expected behavior:**

This is the weird part. First of all, obviously, this dialog shouldn't be coming up (and apparently at random, or perhaps when some timer expires). But perhaps more importantly, it doesn't matter whether I proceed to unlock the keyring or not. Everything still operates normally. So why does it ask me about it in the first place?

**Other Notes:**

**Comment by bflanagin** [comment]
You are correct, the issue is tied to (at least in part) by autologin. I doubt if the appearance of the keyring unlock message is random, but rather caused by a service or application requesting the key-ring in the background. The fact that it doesn't seem to affect anything is a good sign, 

I suggest looking in both keyring ( Passwords & keys) and startup applications to see if there is any hint as to what is requesting access. You may need to delete all the stored and or remove applications from startup to get rid of the dialog.

All that being said, this isn't a bug, and is expected behavior. If you need further help feel free to chat with the team and the community over at https://chat.pop-os.org/
