### ISSUE TITLE
Cannot Take A Screenshot for All monitor simultanously

### ISSUE THREAD

**Issue by ydhnwb** [pop-os/pop#2307]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
built in screenshot app

**Issue/Bug Description:**
When running multiple monitor, screenshot only provides the primary monitor or secondary monitor.

**Steps to reproduce (if you know):**
Tap PrintScreen button when connected to second monitor.

**Expected behavior:**
Should grab the second monitor too and second monitor.

**Other Notes:**
I am running on laptop. So it might different who run on PC (because laptop have built in display)

**Comment by gregory-opera** [comment]
I don't think this is a bug, but it is also not very clear how to change between displays when taking a screenshot... It took me a second to work it out.

When you press the "print screen" button on your respective keyboard and then select 'Screen' in the screenshot function, you can change which display is captured using the "arrow" keys on your keyboard... You _should_ see a white frame around the display which will be captured using the 'screenshot' tool.

As best I can tell, one cannot take a screenshot of _all_ the displays at once... I tested this on a laptop with two built-in displays, with a third (external) display connected via HDMI.

**Comment by ydhnwb** [comment]
Yes. I change the title and description

**Comment by gregory-opera** [comment]
I just had a thought - the "screenshot" functionality is (now) a part of GNOME itself... Therefore, this design flaw should _probably_ be brought to the attention of the _GNOME developers_, rather than the Pop!_OS developers.

Because this design flaw relates to GNOME - which is just one component of Pop!_OS - it's _probably_ not going to get much traction here... At best, somebody will likely mention this as a design flaw on the GNOME project page on your behalf; at worst, this thread will sit here in limbo forever.

Fortunately for you, GNOME's project page is on the same site as this one!

I don't care enough about this design flaw to mention it myself, but you can do so over here:
https://gitlab.gnome.org/GNOME

**Comment by gregory-opera** [comment]
> FWIW, Shift + PrintScreen captures all monitors.

Oh wow, it even retains the screen layout when you do this (the lower image on the left is the second built-in display on my laptop, the image on the right is my external display!

Have you seen this, @ydhnwb ?
