### ISSUE TITLE
Can't login with 22.04, loops back to login screen every time

### ISSUE THREAD

**Issue by yatahaze** [pop-os/pop#2524]
I've tried to update to 22.04. I've also tried a fresh install to 22.04. Every time I land on a login screen that doesn't work. After logging in, it just waits and returns me back to the login screen.

- I don't know the best way to recover my system from this event.
- I don't know what details to provide to help debug this. The system is basically dead at this point.

Any help would be appreciated. Thank you!

**Comment by leviport** [comment]
Sounds like it could be a number of things, but perhaps this article will help: https://support.system76.com/articles/login-loop-pop

**Comment by leviport** [comment]
Did you try adding another user account like that article recommends? That's definitely worth a try, and in narrows down the problem to a config file in your main user's home directory.

If you're looking for more options, the recovery partition might be of some help: https://support.system76.com/articles/pop-recovery. I'd recommend backing up your files before going too much further though.

Although if you're taking more drastic action, going back to 21.10 isn't recommended since it goes EOL the day after tomorrow. I think a Refresh OS is probably the best fix. It will preserve your files, keep you on 22.04, and it _should_ fix the login loop, as long as the problem isn't the configuration in your main user account (which we should be able to determine by adding another user, as mentioned above).

**Comment by yatahaze** [comment]
Well no, mainly because I had all these issues on a completely fresh install on a new disk. 

If I upgrade my OS I'm stuck in a terminal only and can't get any work done, etc. so if I do that I need to be confident I can restore out of it or have a proper fix that will work.

**Comment by flashdens** [comment]
I've also started encountering this issue today, tried most likely every solution i could find on the Web, but nothing worked in a direct way. The additional user creation method should work, because I managed to start a gnome dekstop session on the new account, but the problem is that I dont know what to do next. xd
Help of any kind would be appreicated.

**Comment by flashdens** [comment]
Bingo! It was the .profile dir which caused me all the pain. It was not listed on the site, so I would have no idea without your help. Thanks a lot! I wonder if the solution will be permanent tho

**Comment by rquinlivan** [comment]
I was unable to upgrade from 21.10 to 22.04. I ended up having to do a clean install to get to 22.04.

**Comment by yatahaze** [comment]
I did a bunch of backups to be safe. I went and upgraded again and I was surprised that it just worked. Maybe some bug fixes happened in the background since I last tried updating.

Just to be clear I tried a totally fresh install, full wipe of my OS drive, etc. and it wasn't working. But this update worked this time.
