### ISSUE TITLE
[ASUS laptop] Battery level indicator not updating

### ISSUE THREAD

**Issue by FluxZA** [pop-os/pop#2609]
**Distribution (run `cat /etc/os-release`):**
22.04 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Unknown

**Issue/Bug Description:**
The battery level indicator is stuck at the battery level when my laptop boots. Any charging/discharging that occurs is not shown. After restarting the value changes to the new level and is once again stuck.

**Steps to reproduce (if you know):**

**Expected behavior:**
The battery level indicator should change as the level of the battery changes.

**Other Notes:**
I saw a [discussion](https://www.reddit.com/r/pop_os/comments/x22io7/battery_indicator_does_not_update/) on reddit which suggested that this is linked to Asus laptops. I am also using an Asus laptop.

**Comment by linuxgnuru** [comment]
See if removing the battery history data might fix things:
`sudo rm /var/lib/upower/*`
Once this data has been removed it may take a few charge / discharge cycles to recreate the data.

**Comment by jacobgkau** [comment]
Did you try the solution that @linuxgnuru suggested while on the new kernel?

**Comment by FluxZA** [comment]
I have tried the solution given by @linuxgnuru but it did not work. Battery level updates on both 5.17.15 & 5.18.10 kernels, but not on 5.19.0

**Comment by singmnj** [comment]
I am facing the exact same issue on My ASUS TUF A15 FA506IU.
The issue started with kernel upgrade to 5.19 (5.19.0-76051900-generic)
It works fine with 5.18 when using older kernel to boot.

**Comment by linuxgnuru** [comment]
Do the systems charge when powered off or suspended? Are they not charging at all or just if the battery is between 90-100%?

**Comment by singmnj** [comment]
> Do the systems charge when powered off or suspended? Are they not charging at all or just if the battery is between 90-100%?

The System charges at all times, when powered on/off or suspended. The battery is working just fine. It's just that the battery indicator updates only on rebooting or turning on the laptop. The battery percentage remains stuck to whatever value was there on boot because of this I have to keep it plugged or else it will just shut down without any indication.

While searching for this issue, I found this:
[https://ask.fedoraproject.org/t/battery-charge-indicator-broken-on-certain-asus-motherboards-automatic-suspend-doesnt-work/26119](url)
If this is indeed the case and kernel-5.19.9 resolves the issue, any idea when we can expect an update to this kernel version?

**Comment by FluxZA** [comment]
@singmnj I had success blacklisting the asus_ec_sensors module which is discussed in the post you linked.

**Comment by singmnj** [comment]
The Issue is fixed for me with the latest update, which updated the kernel version to 5.19.16 (5.19.16-76051916-generic) .

**Comment by FluxZA** [comment]
As mentioned by @singmnj , the issue is fixed in kernel 5.19.16
