### ISSUE TITLE
Apt script broken on Ubuntu by #2651

### ISSUE THREAD

**Issue by leviport** [pop-os/pop#2652]
https://github.com/pop-os/pop/pull/2651 should have accounted for Ubuntu (when the `--dev` flag is present).

**Comment by jacobgkau** [comment]
> (when the `--dev` flag is present).

What do you mean by "the `--dev` flag"? It looks like the script used to check if the `apt-manage` command is available, which we can add back, or we can check the ID in `/etc/os-release` to see what OS is running. I see a `--dev` flag higher up in the script, how should it be accounted for in the modified section?

**Comment by jacobgkau** [comment]
Huh, I see that we use `/staging-ubuntu` instead of `/staging` if `--dev` is present. Do you think it would be better to just do everything with the flag instead of what was being done before? And is `--dev` the appropriate flag if it's basically an Ubuntu flag? Or would it be better to replace the flag with checking `/etc/os-release` so you don't need to use the flag anymore?

**Comment by leviport** [comment]
Something other than `--dev` would definitely be an improvement. If the script used `/staging-ubuntu` automatically, then that would be even better.

**Comment by leviport** [comment]
Oh another thought: we may also want to change the `--dev` flag in the `launchpad` script as well, so it remains consistent. It'd probably be good to see which other scripts may have used that flag.

It kinda makes me wonder how the `--dev` flag was decided on initially, but that knowledge is probably lost to the sands of time.

**Comment by jacobgkau** [comment]
> It kinda makes me wonder how the `--dev` flag was decided on initially, but that knowledge is probably lost to the sands of time.

Might have been that the `system76` PPA was for Pop!_OS and the `system76-dev` PPA was for Ubuntu (the `-dev` one existing first.)
