### ISSUE TITLE
trackpad scrolling not working after logging back in

### ISSUE THREAD

**Issue by cunctator00** [pop-os/pop#267]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

**Issue/Bug Description**
If I log out and then log back in, the trackpad scrolling stops working,

**Steps to reproduce (if you know)**

**Expected behavior**

**Other Notes**

**Comment by jlwallen** [comment]
I can verify this. I'm having the same issue with two different track pads:

Logitech T650 and MS Arc Mouse (bluetooth edition).

This is a 5.x kernel issue. I booted into the 4.18 kernel and the problem is gone. 

From cat /etc/os-release:

NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
