### ISSUE TITLE
apt purge not completely removing Thunderbird

### ISSUE THREAD

**Issue by Bug-Report1** [pop-os/pop#2723]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
I'm assuming this was you? https://github.com/pop-os/pop/issues/2721

Don't open duplicate issues, please. And I explained why I closed that first report. You provided no information, other than an issue title. That is not a good bug report. 

I also explained how to get that issue reopened. You have to edit your post and actually fill out the issue template. Bug reports need information.

 I'm also going to close this issue because you still have not filled out the issue template. If you edit your post and provide more information, I will reopen it. 

Please do _not_ [make comments on unrelated issues](https://github.com/pop-os/pop/issues/2704#issuecomment-1355239586) or open duplicate reports like this one.
