### ISSUE TITLE
Can I get Pop! OS release with vanilla GNOME desktop?

### ISSUE THREAD

**Issue by Anifyuli** [pop-os/pop#2785]
Hello, Pop! OS developer.
If I can make a wish, can I get release of Pop! OS with vanilla GNOME as main desktop for Pop! OS spin-off? I like COSMIC Desktop, but it make a ugly interface on my laptop and Application Menu overlap with dock in small resolution (my screen is 1366 * 768). I can disable it, but I miss with Pop! OS 20.04 version because similar with vanilla GNOME interface. Can you all realize it for some people with small screen but wants to using Pop! OS or someone who dislike with customized GNOME desktop? 
I wish this issue readed. Thanks for read my issue 🙏🏼
Sorry my English

**Comment by leviport** [comment]
It sounds like there are two elements to this issue, so I'll address each.

The first is that the application library doesn't scale well on smaller resolution screens. That issue is being tracked here: https://github.com/pop-os/cosmic/issues/314

The second is the request to have Pop without COSMIC. That may be something one could accomplish themselves by disabling all of the COSMIC extensions, but a vanilla GNOME Pop is not something that is currently being planned.
