### ISSUE TITLE
Low Disk Space on "efi" warning

### ISSUE THREAD

**Issue by joaobarcia** [pop-os/pop#2887]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

```

**Issue/Bug Description:**

A `Low Disk Space on "efi" warning` every time Pop OS launches

![Screenshot from 2023-05-05 20-54-02](https://user-images.githubusercontent.com/6717014/236557849-57dba583-95c3-43e4-95c1-b4403a1e2a89.png)

**Other Notes:**

I have always installed and updated Pop OS via the standard methods. The machine is a Dell XPS 17 and only has Pop OS on this disk.

Here are the folder sizes on `/boot`

![image](https://user-images.githubusercontent.com/6717014/236558614-2bac811a-7b77-4a05-9990-a9a131d07b6c.png)

Is anything here out of the ordinary? Should I submit further information on the contents of each folder?

Thank you very much in advance

**Comment by mariaeiou** [comment]
I have the same issue on my Dell Latitude 5410 with an older pop-os distribution up to the point that it could not finish an update because of the lack of storage on efi and broke my bootloader which was a pain to fix via live-usb...

`NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
`
It would be great if there is a way to fix this without a complete reinstallation of the system...

**Comment by leviport** [comment]
Changing the initramfs compression method to `xz` rather than `zstd` might help: https://github.com/pop-os/default-settings/issues/168
