### ISSUE TITLE
Password visible in plain text after logging out / shutting down / session close

### ISSUE THREAD

**Issue by epistax** [pop-os/pop#292]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Issue/Bug Description:**
The password used to log in is visible in plain text after switching to session Ctrl+Alt+F1. It appears after the drive decryption prompt, which also remains visible in this session. Difficult to reproduce (see below).

**Steps to reproduce (if you know):**
Could not reproduce. I would suggest:
* Starting in the state system76 ships their laptops
* Boot; enable disk encryption when prompted
* Follow prompts to get set up. Create a new user
* Once logged in to a desktop session, switch with Ctrl+Alt+F1

After subsequent reboots, the Ctrl+Alt+F1 combo provides an X session login rather than a plain terminal.

**Expected behavior:**
No passwords would be visible in plain text.

**Other Notes:**

**Comment by mmstick** [comment]
Are you certain that you saw a password, and not just the password prompt? Cryptsetup never prints the password to a terminal. Only a prompt.

**Comment by epistax** [comment]
Yes. To be precise, it wasn't the disk password. I did not see that. It was
the password for the account I created during setup, twice.

**Comment by mmstick** [comment]
So GNOME Initial Setup is writing the passwords you enter into it?

**Comment by epistax** [comment]
I can't be sure. I had already logged in at least one session after, so it
may have come from they. If I were trying to reproduce this, I would check
at each opportunity to see what's on the Ctrl+Alt+F1 screen.

**Comment by lumi-sch** [comment]
It's not just initial setup. Every time I log out or shut down my Laptop, it shows the password I used for logging in - and it does so in a particularly large font.

**Comment by jverne** [comment]
I can confirm that I see what @lumi-sch reports. On my Lenovo lappy when I logout or shutdown it switches briefly to a console view, and the last line on it, mid-screen, is my password. Since I use the same password for my account and unlocking the disk, I'm not sure which it is.

**Comment by mmstick** [comment]
I still haven't been able to replicate this.

- When installing, it's already on tty1
- In initial setup, initial setup is running on tty1
- As soon as initial setup completes and it reverts back to GDM, it is still on tty1
- Upon logging in, tty1 remains as GDM
- On shutting down or starting up, no messages

**Comment by awingedturtle** [comment]
I don't know if this will help or detract, but I'm glad I'm not the only one experiencing this (or, maybe I shouldn't be glad).  

Here is my experience, for replication purposes.  I received a new Oryx Pro yesterday with Pop!_OS 18.04 LTS.  After the FDE setup, I chose the option to shutdown and create a user later.  On next boot up, I created a user and logged in.  The only things I did then were navigate around a bit, create a folder and a new document, and rename the computer.  When I chose log out from the menu at the top right, I was prompted with a window to wait 60 seconds or log out immediately.  I chose to log out immediately, and the screen flipped to a terminal window that displayed my user password (not my FDE password, since reusing passwords is bad opsec, especially with your FDE and user ID on the same box), and then the screen flashed and brought me back to the desktop.  I tried the log out sequence again, and again the terminal appeared with my password written out on several lines, but then I was sent to the login screen.  I logged back in and tried the same log out process a few times in a row with the terminal window appearing each time, displaying my password on one or more lines, then sending me to the login screen.  After a reboot, the terminal window no longer appears.  In case it's relevant, I have a GTX 1070, but was using the Intel graphics as suggested by the setup process.

**Comment by reivaxtech** [comment]
@awingedturtle I had installed Pop a day ago and I experienced the same issue. It was when I logged out and chose to log out immediately. I then saw my password.

**Comment by abrosen** [comment]
I encountered the issue tonight.  The only thing I have to add which I don't think was relevant was that I discovered it when I was trying to adjust the text scaling.

I captured it on video, since I wasn't sure if anyone else found it.
https://photos.app.goo.gl/oK9F9hP2mnbvx9qm9

That is the real password for my machine, but I haven't used it anywhere else, so I'm not worried about it being spread around the internet.  I was really proud of that password too.

**Comment by jackpot51** [comment]
@mmstick @abrosen from that video, it almost looks like input is being directed to both GDM and the first VT. 

If the issue is coming from GDM, this may provide more information:

- Provide the output of `apt-cache polity gdm3`
- Run `sudo apt install gdm3=3.28.2-0ubuntu1.3 libgdm1=3.28.2-0ubuntu1.3 gir1.2-gdm-1.0=3.28.2-0ubuntu1.3`
- Attempt to reproduce bug again
- Run `sudo apt upgrade`
- Verify bug is present

We have a patched version of GDM3, so it is conceivable that these changes have caused this.

**Comment by abrosen** [comment]
`gdm3:
  Installed: 3.28.2-0ubuntu1.3pop1
  Candidate: 3.28.2-0ubuntu1.3pop1
  Version table:
 *** 3.28.2-0ubuntu1.3pop1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.28.2-0ubuntu1.3 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
     3.28.0-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
`

I will be back with the rest

**Comment by abrosen** [comment]
Bug is still present after downgrade and upgrade.

**Comment by mmstick** [comment]
Upstream bug: https://gitlab.gnome.org/GNOME/gdm/issues/408

**Comment by bittercold** [comment]
I'm very new to this environment, please bear with me. 
I was just curious about a of couple of things.

Does the patch in the upstream Gnome issue stops things from being printed or stops keyboard input from being sent to the console in the first place?

Also, the prime suspect seems like failure of plymouth to deactivate console because it is not in a fully active state itself. But how can it not be active, if it runs way before Gnome? Can it accept the disk encryption password and still not be in an "active" state? Sorry if this is a dumb question, but like I mentioned, I'm new, and from my shallow understanding I would except plymouth to be up when we're entering disk password, and gone by the time we're entering login password.

As a side note, I actually don't mind text screen at all, so is it possible to disable plymouth locally, or is it more or less required in the entire pop_os boot process?

**Comment by mmstick** [comment]
@bittercold It's not the decryption password that's getting leaked. GDM does seem to receive the password on TTY1, and Plymouth activating after GDM has loaded would cause the password you typed to not be hidden. The Plymouth fix will be out soon.

Plymouth is only there for the device decryption screen. Otherwise, our customers would be met with a lot of small text asking for the device password. You can disable it by removing the `splash` option from the kernel boot parameters.

**Comment by bittercold** [comment]
Oh yes, I realize that it's the login password, that's what I experienced myself.
What I meant is since plymouth is there only for device decryption screen, doesn't that happen long before GDM loads? So it should have been deactivated before we even get the login screen. I just didn't understand the hypothesis about plymouth never fully activating (and this ignoring deactivate command). Since we're entering decryption password before GDM loads, plymouth must be have been active.

In any case, thank you for the information, especially since it's the weekend. I'll try removing splash and see if I still run into the issue.

**Comment by mmstick** [comment]
The Plymouth fix for this is currently in proposed, so expect to see an update soon.

**Comment by mbwatson** [comment]
I experienced this today, too, after an update. This temporary fix at least gives your keyboard shortcut back: `sudo kbd_mode -s`.

Found this [here](https://unix.stackexchange.com/questions/146060/how-to-disable-alt-arrow-switching-of-virtual-consoles#186016).

**Comment by jackpot51** [comment]
This should be fixed in Pop!_OS in plymouth `0.9.3-1ubuntu7.pop0`

**Comment by goodmami** [comment]
@jackpot51 Is it really fixed though? I just saw my passwords when switching TTYs (actually I did Ctrl-Alt-F10, whatever that does, then switched to TTY 3). More specifically, I saw the passwords of both logged-in users (the only two users on the system, as well), and the second user's password was displayed several times (I guess they logged in and out a few times). I'm using `plymouth 0.9.3-1ubuntu7.pop0`:

```
goodmami@tpy:~$ apt show plymouth
Package: plymouth
Version: 0.9.3-1ubuntu7.pop0
...
```

Were other components affected? I hadn't updated my packages in about 2 weeks (e.g., mid-January 2019), so maybe something else was causing the problem?

**Comment by jackpot51** [comment]
It is possible that this is still an issue. I have seen this issue in other GNOME systems, I believe it to be a GDM bug:

- https://bugzilla.redhat.com/show_bug.cgi?id=1178806
- https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1803993

**Comment by gshiva** [comment]
Brand new install of Pop OS and saw the same issue

**Comment by davidplrobinson** [comment]
I can confirm I have just encountered this on a new install :/

**Comment by ForestJay** [comment]
This might not just be Pop OS. My newest System76 w/ 18.04 does this too!

**Comment by vicstr** [comment]
Also encountered on a UbuntuDDE 20.04 new install

**Comment by jacobgkau** [comment]
Fixed by https://github.com/pop-os/gnome-shell/pull/40.
