### ISSUE TITLE
Gnome Shell causing laptop to freeze - consuming a lot of CPU

### ISSUE THREAD

**Issue by bonej079** [pop-os/pop#3115]
**(1) Issue/Bug Description:**

Gnome Shell causes laptop to freeze

**(2) Steps to reproduce (if you know):**

Laptop freezes. Use Ctrl-Alt-F4 to log into a shell and kill process /usr/bin/gnome-shell|dconf worker 

Use Ctrl-Alt-F1 to log back into original shell

**(3) Expected behavior:**

This process should not hog the CPU

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
**(5) Gnome Shell version:**

GNOME Shell 42.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1682616779~22.04~b5accce
  Candidate: 1.1.0~1682616779~22.04~b5accce
  Version table:
 *** 1.1.0~1682616779~22.04~b5accce 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Installation medium

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2 x 1920*1080 (16:9)

**(9) Other Installed/Enabled Extensions:**

NA

**(10) Other Notes:**

![2692f21e-f170-44dc-9e48-2f0ca8191b25](https://github.com/pop-os/shell/assets/11914535/1b42f89f-711f-4a75-aab6-faf82251273e)

**Comment by mmstick** [comment]
Watch gnome-shell logs with `journalctl -o cat -f /usr/bin/gnome-shell`. Also disable all third party GNOME extensions, since they are executing in the same process.

**Comment by bonej079** [comment]
OK, I captured the journalctl as requested. Only one GNOME extension, Ubuntu AppIndicators, which makes status bar icons visible (maybe there is a better way?). Thanks for taking care of this issue.
[gnome-shell.txt](https://github.com/pop-os/pop/files/12420708/gnome-shell.txt)

**Comment by janicki** [comment]
I experience essentially the same, every few days.  The system goes into an infinite loop writing syslogs.  Killing gnome-shell from another machine fixes it.  Here is where the problem seems to begin, then the last few lines get very repetitive.  (My /var/log/syslog file has 2GB that is mainly copies of the JSAPI log and stack trace.)  Hope this helps.

```
Aug 22 15:42:57 thelio gnome-shell[406914]: Window manager warning: last_focus_time (745014185) is greater than comparison timestamp (745014017).  This most likely represent
s a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Aug 22 15:42:57 thelio gnome-shell[406914]: [popx11gestures@system76.com] Connection with Touchégg established
Aug 22 15:42:57 thelio NetworkManager[1296565]: <info>  [1692733377.1903] agent-manager: agent[e81e4d9b5becbf7a,:1.3713/org.gnome.Shell.NetworkAgent/1000]: agent registered
Aug 22 15:42:57 thelio systemd[2203]: Started dbus-:1.5-org.gnome.NautilusPreviewer@243.service.
Aug 22 15:42:57 thelio kernel: [744941.452859] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Failed to grab modeset ownership
Aug 22 15:42:57 thelio systemd[2203]: Started dbus-:1.5-org.gnome.ArchiveManager1@215.service.
Aug 22 15:42:57 thelio gnome-shell[406914]: DING: Detected async api for thumbnails
Aug 22 15:42:57 thelio gnome-shell[406914]: DING: GNOME nautilus 42.6
Aug 22 15:42:58 thelio NetworkManager[1296565]: <info>  [1692733378.2430] manager: startup complete
Aug 22 15:42:58 thelio systemd[1]: Finished Network Manager Wait Online.
Aug 22 15:43:03 thelio gnome-shell[406914]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor 
or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has
 been blocked and the JS callback not invoked.
Aug 22 15:43:03 thelio gnome-shell[406914]: The offending signal was notify on MetaStage 0x556cd887b440.
Aug 22 15:43:03 thelio gnome-shell[406914]: == Stack trace for context 0x556cd88d7190 ==
Aug 22 15:43:03 thelio gnome-shell[406914]: #0   556d0cc571c0 i   resource:///org/gnome/shell/ui/main.js:777 (15822b5ecce0 @ 243)
Aug 22 15:43:03 thelio gnome-shell[406914]: #1   556d0cc570f0 i   /usr/share/gnome-shell/extensions/pop-cosmic@system76.com/extension.js:277 (41f9be7b00 @ 131)
Aug 22 15:43:03 thelio gnome-shell[406914]: #2   556d0cc57030 i   resource:///org/gnome/shell/ui/switcherPopup.js:136 (3a550943cc40 @ 867)
Aug 22 15:43:03 thelio gnome-shell[406914]: #3   556d0cc56f78 i   resource:///org/gnome/shell/ui/windowManager.js:1688 (b385142d790 @ 493)
Aug 22 15:43:03 thelio gnome-shell[406914]: #4   7fffe64e8c90 b   self-hosted:1178 (15822b5b0a10 @ 492)

```

**Comment by bonej079** [comment]
Same problem today. This time, there is a different error. I am attaching the log; maybe it makes sense.

Hope it helps, and thank you!

[gnome-shell3.txt](https://github.com/pop-os/pop/files/12454865/gnome-shell3.txt)

**Comment by BarbzYHOOL** [comment]
i never had so many freezes and crashes (corrupting my partitions several times, never happened before in 10 years) until i used pop os

i started telling people to avoid it now that i'm kinda stuck with it and nothing is being done for any issue

just ranting coz it sux

**Comment by leviport** [comment]
>nothing is being done for any issue

Nonsense. I'm sorry to hear your experience has been negative, but it's a rare occurrence. If we knew what was giving you trouble, we'd either fix it or try to help you resolve it.

>just ranting coz it sux

This is an issue tracker, not a social forum. Please refrain from off-topic ranting in the future. Such rants in a thread where we're actively trying to help other users is not only unproductive, it's counter-productive.

**Comment by BarbzYHOOL** [comment]
> we'd either fix it or try to help you resolve it.

Really not, i asked for help (and i'm not alone) several times, like 5 at miniminum, here and on reddit, nothing except some snarky remarks. My issues have even been closed without a fix, showing how much disdain there is for people not using system76 computers most likely (my only hypothesis)

For example, these freezes are not a rare occurrence, google it up, hundreds of people with different hardware having the same issue for 2 years. No solution.

**Comment by mmstick** [comment]
@BarbzYHOOL Please read the [Code of Conduct](https://github.com/pop-os/code-of-conduct). Assume good intentions. There has never been any disdain towards people not using System76 computers. It's a baseless accusation. If that were true, I would not have commented [here](https://github.com/pop-os/pop/issues/3115#issuecomment-1690143484), nor virtually anywhere else.

It doesn't matter how many issue reports are created. Unless someone on the team is able to reproduce it, it will remain impossible for any one of us to resolve it. I have never experienced GNOME Shell freezing in 22.04 on any of the systems in my household.

**Comment by bonej079** [comment]
I am sorry that this issue has turned into a disrespectful discussion. I have found a helpful community that tries to help me the best way they can. I resort to opening an issue when I find myself in a position where I cannot figure out what's going on, and I rely on the expertise and goodwill (and there is a lot of both) within the community to help me figure out the issue. Since the comments above are not helpful, I have decided to close the issue. Thanks, @mmstick, for your help. I am immensely grateful.

**Comment by bonej079** [comment]
Closing the issue due to off-topic disrespectful remarks.

**Comment by BarbzYHOOL** [comment]
> @BarbzYHOOL Please read the [Code of Conduct](https://github.com/pop-os/code-of-conduct). Assume good intentions. There has never been any disdain towards people not using System76 computers. It's a baseless accusation. If that were true, I would not have commented [here](https://github.com/pop-os/pop/issues/3115#issuecomment-1690143484), nor virtually anywhere else here on GitHub, Reddit, Lemmy, Mastodon, etc..
> 
> It doesn't matter how many issue reports are created. Unless someone on the team is able to reproduce it, it will remain impossible for any one of us to resolve it. I have never experienced GNOME Shell freezing in 22.04 on any of the systems in my household. In fact, I've not heard of anyone on the team encountering system freezes like this. I'd see constant complaints about this on Reddit if it were common.
> 
> In this case, it looks to be an issue between Variety and various other gnome-shell extensions. The backtraces from gnome-shell aren't often useful for finding the root cause. It needs to be easy to replicate from a clean install.

Yeah, nice blabla, i'm just gonna remove pop os once and for all and stop having freezes and partition corruption (ah yes because when it freezes, REISUB doesn't work of course), like many people recommended on reddit

Almost two years with the same issue, hundreds of people complaining about freezes, but I hope I am not too disrespectful, at least not as disrespectful as having data corruption

It's almost like we are at fault if professional paid developers cannot reproduce the issue.

PS: it's always you answering the same thing for two years, even on reddit. We would really prefer if you came up with "no we're never gonna fix all those freezes, just move on dude". While typing all of this I've gotten several freezes. Not to mention that I cannot use suspend anymore since a recent update (may not be POPOS' fault but Ubuntu's). Feel free to never reply, I won't read it anyway because I know the answer already.

**Comment by leviport** [comment]
>i'm just gonna remove pop os once and for all 

Sounds good, I hope your next OS works much better for you.

>Almost two years with the same issue

It is not the same issue. If you had read the other thread, which also had to be closed and locked due to breaches of the code of conduct, you would have noticed that most reports ended up being bad RAM. Others had a multitude of different causes. The reality is that an operating system is a very complicated thing, and it's a complicated thing that's being run on a vast variety of general purpose PCs out there. Bugs are going to happen. Compatibility issues, hardware failures, individual configuration issues, or heck, even cosmic rays could be responsible for any given freeze event. Just because it's reliably reproducible on your hardware doesn't mean it will happen on anything we test here. 

>It's almost like we are at fault if professional paid developers cannot reproduce the issue.

No one ever implied that. We just don't have anything to go on. If I saw even a single freeze on any machine in my lab, I'd  investigate until I got to the bottom of it. The last several times I did find a freezing machine, I traced it back to faulty hardware. The behavior you're seeing is unfortunate, and I'm sure it's very frustrating, but it's not widespread.

>Feel free to never reply, I won't read it anyway because I know the answer already.

Excellent, I'm locking this thread then. Farewell, Barbz.
