### ISSUE TITLE
after restart pop os 18.04 its black screen!!! 

### ISSUE THREAD

**Issue by adismmhonoredk** [pop-os/pop#332]
**Distribution (run `cat /etc/os-release`):**
 
 POP_OS 18.04
desbian
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
after upgrade my os it show black screen that says
ubuntu 18.04.1 LTS xps13 tty1 (I install pop os not ubuntu!)
xps13 login:
so I enter my username ... and ask for password
password:
I enter it and its like terminal!!!
what shoud I do?
![image1](https://user-images.githubusercontent.com/42260545/43938897-9223f264-9c7b-11e8-89d1-d3260c7f24ef.jpeg)

**Steps to reproduce (if you know):**

**Expected behavior:**

go to starting page of POP_OS 18.04 and ask me pass ....

**Other Notes:**

Im completely new and noob to Linux ! 
thanks

**Comment by Bananas-Are-Yellow** [comment]
This just happened to me too.

I was prompted to install updates. Pop!_Shop came up and I pressed the button to update the OS. Afterwards, the "Operating System Updates" icon had changed form the Pop!_OS logo to the orange Ubuntu logo.

I restarted, but it came up in terminal mode, just like the original poster. Did I do something to screw things up? How do I get out of this situation?

**Comment by Bananas-Are-Yellow** [comment]
I just followed these instructions to use the Recovery Partition:

https://support.system76.com/articles/pop-recovery/

But that made no difference. It still boots into a full-screen terminal.

HELP!

**Comment by StefanPahlplatz** [comment]
+1

**Comment by jackpot51** [comment]
If you can log in at the terminal, here is what to do to restore your system:

```
sudo apt-get update
sudo apt-get install pop-desktop
```

These commands require networking, please make sure each one succeeds.

**Comment by Bananas-Are-Yellow** [comment]
Thank you @jackpot51 but I was impatient so I reinstalled Pop!_OS from the recovery partition. The laptop only arrived on Monday and by Thursday I had screwed it up. I was messing around with sources.list and sources.list.d, trying to get Canonical Partners to work so I could use Flash, but with no luck. Somewhere along the line, I must have messed things up. Anyway, since I had only set everything up very recently, it didn't take me long to get reinstalled and set up back how I like things.

Thanks for the tip though. If this ever happens again, I know what to do now.
