### ISSUE TITLE
Disk encryption

### ISSUE THREAD

**Issue by nkumar84475** [pop-os/pop#407]
Want to disable LUKS disk encryption that was started at installing pop os

**Comment by mmstick** [comment]
By disable, do you mean converting a LUKS install to a non-LUKS one?

If that's so, this isn't possible -- you have to do a new install without encryption.

If you mean how to install without using LUKS encryption, this is possibly by opting to not provide a disk encryption password.

**Comment by jaw6565** [comment]
Why not just try out other distros from live usb, or vbox

**Comment by jackpot51** [comment]
It is not possible to disable disk encryption without a reinstall

**Comment by alknemeyer** [comment]
Could you comment on whether you think [this solution](https://askubuntu.com/a/1335140) would work? Ie:

1. Boot into a live environment using a USB stick. I used Ubuntu 18.04.
2. Run `sudo cryptsetup-reencrypt --decrypt <device_path>`.

I don't know if that's new functionality introduced since your answer, or if that doesn't work for Pop OS for some reason
