### ISSUE TITLE
Add gnome-shell-extension package : needed by some extensions

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#44]
_From @1LinuxGuy on September 28, 2017 20:12_

Unless you really don't want people changing anything, this package is needed by some Gnome extensions, like Arc Menu. If not installed, it will give an error on install from the Gnome extensions web page. I had to go to the GitHub page of the extension to get the info to correct this.

_Copied from original issue: pop-os/iso#98_

**Comment by isantop** [comment]
Package not found, closing for now since we don't seem to have issues.

**Comment by 1LinuxGuy** [comment]
@isantop 

Package not found ? Are you kidding ?

Open Synaptic, search for "gnome-shell-extensions".

Proof of concept : try to install the extension Arc Menu. It won't work because there are 2 packages missing. gir1.2-gmenu-3.0 being one of them, that is included in the package gnome-shell-extensions, because that package contains Applications Menu. 

Also, try to install the extension Gnome email notification, ti will send you a message saying it needs the package gir1.2-goa-1.0

So, yeah, like I said, if you don't make any changes to the current Pop set up, no, you don't need it. But the minute you make some, the user has to be more experiences in Gnome to know what to do. Same thing in Ubuntu 17.10, when you create a gnome-session.

**Comment by isantop** [comment]
I had searched for `gnome-shell-extension`, which wasn't found.

**Comment by isantop** [comment]
Actually, looking into this, it seems that this is not included because it also installs a large number of additional extensions at the system level, which then can't be removed or upgraded properly. Due to this, we can't include this package in the system by default. It's always possible to install dependencies of extensions manually.

**Comment by 1LinuxGuy** [comment]
@isantop 

Yes, you're right. The gnome-shell-extensions package is a bit of a pain. It's the "default" package set of extension that comes with Fedora, for instance. It's simpler to install this one for a new user. I didn't, because I know what packages I need to install the correct extensions.
