### ISSUE TITLE
How to make changing the brighness to be much smoother ? It hurts my eyes

### ISSUE THREAD

**Issue by cata0309** [pop-os/pop#452]

**Comment by KloudKoder** [comment]
On some platforms, brightness control seems to have one huge step early on, followed by lots of little steps later. The steps should instead be uniform to human perception, which is tough to get right because it's sort of exponential, but could certainly be better in the aforementioned case. Worse, brightness is not directly proportional to pixel value under the sRGB specification. It's a pair of completely unrelated functions taped together. This is an awful UI problem plaguing lots of Linux systems generally, and it needs to be addressed. Finally, it's unclear the extent to which ACPI is involved. At least in theory, the brightness steps could be dictated by the firmware. I just don't happen to know.
