### ISSUE TITLE
Unable to boot on Lenovo v510-15ikb

### ISSUE THREAD

**Issue by ggnorton** [pop-os/pop#496]
Appeared on 18.10 Pop OS
 

Unable to boot after installation WITHOUT encrypt on Lenovo v510-15ikb with added 8 gigs of RAM (12 in total)
Security Boot is OFF, all of the steps from https://github.com/pop-os/pop/issues/301 didn't help

Just a regular install from flash drive, reinstall didn't do anything

Edit: Oh and also it's unable to memorise brightness level, so i have to configure it every time i boot in system.

**Comment by SoulCatcher42** [comment]
@ggnorton I have the same laptop with gtx 1050ti graphics card.
You should try to update bios (windows required) [link](https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/legion-series/legion-y520-15ikbn/downloads/ds121057). then try pop os 19.04  instead of 18.10.

Honestly don't know, what's of there solutions resolved problem, but for me after updating firmware i could install Ubuntu 19.04 and Pop 19.04 and it runs perfectly with Nvidia-prime by default.

If you have any questions, you can write to me on [telegram](https://t.me/Soul_Catcher).
