### ISSUE TITLE
No way to go back when you click to set up an enterprise account.

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#56]
_From @MooShoe on July 4, 2017 0:18_

**Reporter info**

```
 * Distribution - Ubuntu 17.04
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Actual issue**
When you are setting up your account, there is an button to set up an enterprise account. (or something like that) Clicking the button takes you to the page, but you can't go back to setting up a regular account without rebooting. 

I'm not sure if that makes sense?

**Steps to reproduce (if you knew)**
Click that button.

**Expected behaviour**
When I click the back button it should take me to the regular accounts page instead of the slide before your chose to set it up.

**Other Note (feature-request, question, etc...)**

_Copied from original issue: pop-os/iso#35_

**Comment by isantop** [comment]
_From @kylerchin on July 10, 2017 4:38_

You can simply click on the activated button to return.
If you need a bit of help, you can watch this.
https://youtu.be/INJf0P8caL8

**Comment by isantop** [comment]
_From @ryanleesipes on July 11, 2017 20:23_

I don't think that is especially obvious, although that is good that you figured it out @kylerschin - we need to have the text at the bottom (where the button is), change when you choose to set up an enterprise account.

Also, what is an enterprise account? :wink:

**Comment by isantop** [comment]
_From @kylerchin on July 13, 2017 16:6_

Do you want to close this issue? What steps should we take? Any UI Improvements you want? @ryanleesipes @cassidyjames @Xeboc

**Comment by isantop** [comment]
_From @WatchMkr on July 14, 2017 16:3_

@kylerschin The solution to this is for the "Previous" button to return the user to the "Account Setup" page rather than back to online accounts.

The "Enterprise Account" button can still toggle on/off but at least "Previous" will do what's expected.

**Comment by isantop** [comment]
_From @ryanleesipes on July 14, 2017 17:58_

Agreed, @kylerschin this is an excellent thing to try and tackle!

**Comment by jacobgkau** [comment]
There is an upstream issue open for this here: https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/issues/63 

Upstream seemed to be against changing the flow of this page, and instead said that the theme needs to be fixed if it's difficult to tell that the button is a toggle that can be turned back off. They did change the label from `Set Up Enterprise Login` to just `Enterprise Login`, which sounds less like an action (button) and more like a toggle.

In Pop!_OS 20.04 LTS, we don't display the `Enterprise Login` button by default at all, because that button is only displayed if `realmd` is installed, and we don't install `realmd` by default. We do have an `Enterprise Login (Kerberos)` option on the Online Accounts page (which appears first.) Here's what things look like in Pop by default:

![IMG_20200804_163106-small](https://user-images.githubusercontent.com/7199422/89353304-5abadc00-d673-11ea-9b2d-9ef867cb9fde.jpg)

![IMG_20200804_163650-small](https://user-images.githubusercontent.com/7199422/89353350-6efed900-d673-11ea-852e-76ffeb4c35ef.jpg)

I shut down (without completing setup), chrooted into the system from a live disk, and installed `realmd`, and then the `Enterprise Login` button showed on the next boot:

![IMG_20200804_164450-small](https://user-images.githubusercontent.com/7199422/89353463-aa99a300-d673-11ea-81d5-e2f7d3ff2c0d.jpg)

![IMG_20200804_164455-small](https://user-images.githubusercontent.com/7199422/89353472-ad949380-d673-11ea-99ea-a284a3aabfda.jpg)

Given that this button would never appear on a default install, this doesn't seem like an issue in the context of Pop!_OS anymore. The same toggle is used in Settings -> Users (when adding a new user if `realmd` is installed), but in that case, clicking `Cancel` and then `Add User...` again does get back to the local form in the event the user doesn't understand this is a toggle.
