### ISSUE TITLE
Activities doesn't activate when hovering with mouse pointer

### ISSUE THREAD

**Issue by matiasrivera** [pop-os/pop#60]
I've been using gnome shell for a couple of years and I find very convenient that the "activities" screen activates when hovering on the top left corner with mouse pointer. This doesn't seem to work with Pop_OS!. Is it something I can configure?

Regards,

Matías

**Comment by isantop** [comment]
In Pop_OS, we disable the top-left hot corner by default as it can create a jarring, user-hostile experience for users unaccustomed to this behavior. It can be enabled by installing GNOME Tweaks, and toggling it on in the Top Bar section. This is something that may be moved to the main settings app in a future version of Pop_OS.

A bit of rationale:

If a user misses a target in the top left of the screen (for example, a browser back button or a toolbar item) and accidentally hits the corner of the screen, having it automatically switch contexts to the overview is a very jarring thing to have happen by default, since the user is trained to associate actions with a click, while they did not yet click. This leads to the feeling that the system is doing things without the users input, which is a bad thing to have happen.

If, however, this happens by accident after a user has explicitly enabled the setting, then they know what input caused it and why it happened without them "triggering" it with a click. Therefore, having this be opt-in functionality educates the user about the potential action that can be triggered, and shifts the burden onto the user for being responsible for this.

**Comment by 29axe** [comment]
@isantop Hi! I tried your suggestion by activating it in the Gnome Tweaks, but it was already enabled. I tried disabling it and re enabling it but still not working. I tried using alt+f2 "r" after each change and still not hot corner. Running pop-os 17.10 on VirtualBox and 2 monitors (for information it's working on another Ubuntu VM with only Pop theme and icons installed).

**Comment by isantop** [comment]
When you try to activate it, are you pressing the mouse into the corner? If not, give that a try. There's a fairly high activation threshold.

Otherwise, it sounds like an extension you have might be inhibiting it.

**Comment by 29axe** [comment]
I will investigate. Thanks for the tip.
