### ISSUE TITLE
Clicking item on desktop freezes everything but the mouse

### ISSUE THREAD

**Issue by FetidDischarge** [pop-os/pop#742]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Made a folder on the desktop, and after clicking it everything locked up except the mouse. SysRq rebooted it. After reboot clicking the folder from the desktop again caused it to hang. 

**Steps to reproduce (if you know):**
Make a folder on the desktop. Click it.

**Expected behavior:**
Everything except the mouse locks up.

**Other Notes:**
This is a brand new installation of Pop. I'm a noob.

**Comment by maxdvlg** [comment]
Hello, kind of the same issue for me.

I made the requested update published with the push notification on the popshop today and when i start my laptop ( xps 15 9570 - pop 19.10 ) few seconds after i'm on the desktop if i click the top panel for example it seems to disable everything i can move the mouse but everything else seems frozen and i must restart with the power button.

ps : before i installed the update received by the push notification everything was working fine. I reinstalled the entire distro thinking i broke something. And the same happened it broke right after i installed the updates

**Comment by fiver22** [comment]
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

issue:
ui freezes except for mouse pointer

steps to reproduce:
right click empty area of 'desktop'; the context menu appears
ui now unresponsive though the mouse pointer can move.

expected behaviour:
ui should continue to be responsive

other notes:
I noticed this or similar before the update today but I can now reproduce every time.
hardware is System: LENOVO product: 20H1004RUS v: ThinkPad E470

**Comment by mmstick** [comment]
There's a fix for this issue which I'll try to get released ASAP today.

**Comment by maxdvlg** [comment]
Thanks Michael, for my case i've received and installed a push update focusing on mutter, everything seems back to normal now =)
