### ISSUE TITLE
Pop!_OS suddenly very sluggish to use...

### ISSUE THREAD

**Issue by FetidDischarge** [pop-os/pop#768]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
After a reboot (forced because it refused to resume properly) the OS has been very sluggish. Chrome in particular is very slow, as is the pop_os discover and app menu. System monitor shows almost no usage of CPU or RAM.

Battery usage is also much higher than it was.

**Steps to reproduce (if you know):**

**Expected behavior:**
Should run faster, like it did yesterday.

**Other Notes:**
It's an acer aspire 5 (Ryzen 7, 8gb ram) that I've dual-booted pop_os on with windows, both of which were clean installs on a clean SSD.

**Comment by cmurray21** [comment]
It's hard to say exactly what may be causing the performance issues. Since the effect came on suddenly, my first guess is something that was recently installed may be the cause.

`cat /var/log/dpkg.log | grep "\ install\ " | grep "2019-11-2*"`

If you run this command in the terminal, it will display a list of recently installed packages. Date is just to narrow results, change it if your region is different.

**Comment by resaba-kaypee** [comment]
This happen to me last week and today, before an update fix the issue but not today.
Im running Pop Os 20.04LTS
It is working fine last night.
I have no idea what causing this I have not install anything new yet
Removing extension or disabling it does not help
syslog does not show anything suspicious either.

**Comment by mmstick** [comment]
@resaba-kaypee  What changes happened since last night?

**Comment by resaba-kaypee** [comment]
This happen to me last week and today, before an update fix the issue but not today.
Im running Pop Os 20.04LTS
It is working fine last night.
I have no idea what causing this I have not install anything new yet
Removing extension or disabling it does not help
syslog does not show anything suspicious either.

> @resaba-kaypee What changes happened since last night?

Actually nothing because I am not connected to the internet the whole night.

But I think I might have fix the issue because now it is back to normal again.

This is what I did today:
There is a blog post in reddit : https://www.reddit.com/r/pop_os/comments/gs2kof/pop_os_slow_recently/
that mentioned about the appIndicator.js I didn't touch the file because it seems it was patched already.

I run `sudo apt update` and update all packages only 80mb, the last time i had an update was the same time I have experience lagging.

Turning on and off did not fix it.

I usually disable app indicator in tweaks but I have enabled it again.

Then i installed Stacer and get rid of Packages caches, crash reports, app logs, app caches, basically I did a clean up it was 4gb in total.

then i restarted and that magically fix the issue.
