### ISSUE TITLE
Extensions showing tray icons in the top bar don't work on Pop OS

### ISSUE THREAD

**Issue by Iiari** [pop-os/pop#84]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```) Pop OS 17.10
 * Related Application and/or Package Version - apt policy $PACKAGE NAME  TopIcons, etc.
```

**Issue/Bug Description**
TopIcons, kstatusnotifier, and other extensions designed to show tray icons in the top bar don't work for me in Pop OS.  I've tried them in fresh installs without success.  They do work on fresh installs of Ubuntu Gnome 17.10.  They also work in fresh Pop OS 17.04 installs.  

When I, based on a Pop OS subreddit post, removed the indicator-application (sudo apt remove indicator-application) then the extensions work.  Again, this wasn't necessary on Ubuntu 17.10.  

**Steps to reproduce (if you know)**
As above

**Expected behavior**
As above

**Other Notes**
Thanks!

**Comment by jackpot51** [comment]
Thanks for this! We will be looking into it - it may be an easy problem to fix.

**Comment by sramkrishna** [comment]
I was not able to duplicate the problem, can you do "alt-F2", type in 'lg', and then go to extensions and click on topicons and then errors and post it here?

**Comment by WatchMkr** [comment]
We have had mixed success with app indicator extensions internally. Our suggested instructions are here: http://pop.system76.com/docs/status-icons/

Going to set as a bite-sized bug in case someone would like to take a look into it.

**Comment by kylecorry31** [comment]
I did some testing with this, and found that Top Icons Plus shows more icons than Ubuntu AppIndicator. For example, Ubuntu AppIndicator will only show dropbox, while Top Icons Plus shows dropbox, hangouts, discord, chrome, and skype.

**Comment by WatchMkr** [comment]
That's interesting. We've found Top Icons Plus to be unstable at times causing odd Gnome Shell behavior. The route might be to look into why Ubuntu AppIndicator isn't showing as much - maybe we can get a patch in there to display the additional indicators.

**Comment by kylecorry31** [comment]
I agree with that, Top Icons Plus also does not seem to standardize icon sizes.

**Comment by kylecorry31** [comment]
I can fix this issue by running:
 
```shell
env XDG_CURRENT_DESKTOP=Pantheon discord
```
or 
```shell
env XDG_CURRENT_DESKTOP=Pantheon skypeforlinux
``` 

It seems like there is an issue with electron putting a legacy indicator up if it does not detect Pantheon, Unity:Unity7, or ubuntu:GNOME (all of those work, replacing Pantheon with their names in my examples above) as seen in this commit to electron: https://github.com/electron/electron/pull/10355/files

**Comment by kylecorry31** [comment]
I submitted a PR to electron to fix it there, but that probably is only a subset of the affected applications, and the fix requires that the apps affected will upgrade their version of electron once it is accepted. There is probably a more elegant solution which combines the legacy status indicators with the ones that AppIndicator supports.

**Comment by WatchMkr** [comment]
Nice find! Is there a way for us to set XDG_CURRENT_DESKTOP for electron apps in the distro for the mean time?

**Comment by kylecorry31** [comment]
OK, so I don't know of an elegant solution to this, it seems like it would be hard to do this:

Append env XDG_CURRENT_DESKTOP=Unity before each application's Exec entry in its .desktop file. I put Unity there, because all electron does is replace that list of desktops (Pantheon, ubuntu:GNOME, etc.) with Unity. So basically the discord.desktop file in /usr/share/applications would be modified to become:

[Desktop Entry]
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=env XDG_CURRENT_DESKTOP=Unity /usr/share/discord/Discord
Icon=discord
Type=Application
Categories=Network;InstantMessaging;


This is probably not the best solution. Maybe we could have a process running that checks to see what applications are running and appends the XDG_CURRENT_DESKTOP variable to the front of applications we know need it. That would probably be the "easiest" solution in my eyes. Other than that we could modify Ubuntu AppIndicator and have legacy status indicators appear in that (that would probably be the best solution, as it targets non-electron apps as well).

**Comment by WatchMkr** [comment]
Found this long thread: https://github.com/Ubuntu/gnome-shell-extension-appindicator/issues/74

**Comment by kylecorry31** [comment]
That makes sense, I will take a closer look at Electron to see if it is easy to replace the XDG_CURRENT_DESKTOP checks tomorrow, as that would be a better solution for all distros which use GNOME. I don't have too much experience with node.js and electron, so I may just have to pull an issue of their repo if I can't figure it out.

**Comment by kylecorry31** [comment]
OK, so I traced the issue down to Chromium (which was why Electron had to do the workaround):

https://github.com/electron/electron/blob/master/atom/browser/ui/tray_icon_gtk.cc#L36 determines if appindicator should be used. I traced this to  https://cs.chromium.org/chromium/src/chrome/browser/ui/libgtkui/app_indicator_icon.cc?l=85 which returns whether appindicator should be used, notice that GNOME is not in the list of true values. This is because GNOME by default doesn't support appindicator (extension needed)?

Not sure what to do beyond this point though.

**Comment by WatchMkr** [comment]
It seems the next step is a PR on Chromium that moves GNOME to the true column (from comments on this thread it's a mistake to blacklist GNOME https://github.com/Ubuntu/gnome-shell-extension-appindicator/issues/74)

And another PR for pop:GNOME to electron since they merge quickly.

@sramkrishna can you check with GNOME folks? I know they're not supporting indicators but just want to check that this is appropriate for folks that want to use Ubuntu's appindicator extension.

**Comment by kylecorry31** [comment]
I can't seem to download the chromium sources on my Internet, if someone else wants to try to make the commit that would be great. It is just that line I linked to a few messages ago. The details to get the sources are here:
https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md 
and the contributing guide is here:
https://www.chromium.org/developers/contributing-code

**Comment by Kadarlatino** [comment]
Got some issue when installed "gnome-shell-extension-appindicator" - after reboot my internet connection is gone, so removed it :(

**Comment by riniculous** [comment]
Not sure if this is related, but I just installed "Clipit" from the Pop Shop, and it also does not showup in the system tray.

**Comment by wmutschl** [comment]
I have similiar issues with nextcloud and proton-bridge

**Comment by tracker1** [comment]
Any progress on the issue... I'm seeing similar and have a few apps that reside as task tray icons I cannot get to.  Teams, Discord, Dropbox and others.

**Comment by WatchMkr** [comment]
I think bug is now resolved. Please install this extension: https://extensions.gnome.org/extension/615/appindicator-support/

We currently don't include app indicator support in Pop by default but we are considering adding it.
