### ISSUE TITLE
Unable to use a second screen on NVIDIA or NVIDIA/INTEL

### ISSUE THREAD

**Issue by sindile** [pop-os/pop#927]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I am unable to get a display on a second monitor connected to the HDMI port

**Steps to reproduce (if you know):**
Using Acer Aspire V17 Nitro (VN7-792G-77YX)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 960M] (rev a2)

Switch either to NVIDIA or Hybrid Graphics (NVIDIA/Intel) and reboot.
Connect monitor to HDMI port

**Expected behavior:**
I was expecting to see a display on my second monitor.

**Other Notes:**
xrandr output
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 381mm x 214mm
   1920x1080     60.00*+  59.97    59.96    59.93  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)

**Comment by harsan81** [comment]
I solved this issue by installing `lightdm` and then configure it as default using `sudo dpkg-reconfigure gdm3` and then choose `lightdm`. Changing fast boot to off at BIOS works as well.

**Comment by harsan81** [comment]
Might be related as well. 

https://www.reddit.com/r/pop_os/comments/g9lkm9/severe_mouse_lag_after_latest_update_of_1910_with/

**Comment by sindile** [comment]
I have tried the suggestion above and still no luck.
I have tried to switch between Hybrid Graphics and Nvidia Graphics and still no luck.
I am not sure what could the problem be (the monitor does work and was working with Ubuntu 18.04 although I was using Wayland).
I did try to use Wayland and no luck there as well.
Not sure if there is anything else I could try.

**Comment by harsan81** [comment]
How about deleting / moving `xorg.conf `out of `~/etc/X11/xorg.conf,` removing the content of `xorg.conf.d` folder and then restart?

**Comment by sindile** [comment]
Removing the contents of xorg.conf.d I could not use the mouse and keyboard at the login screen. I guess I must just forget using a second screen with this laptop for now.

**Comment by harsan81** [comment]
Sorry to make the problem worse. I hope there will be updates or someone with fixes soon.

**Comment by sindile** [comment]
I have made a bit of progress, and getting a picture on the second screen.
![Screenshot from 2020-04-29 20-29-51](https://user-images.githubusercontent.com/1027916/80709130-16a4c200-8aed-11ea-9be5-0b9370ed8563.png)

I cannot though move the windows around or interact with them. If I move a window from the laptop to the second screen the image is distorted and sluggish.
![Screenshot from 2020-04-29 20-30-43](https://user-images.githubusercontent.com/1027916/80709401-831fc100-8aed-11ea-8216-f0ec8029045f.png)

This happens in both GDM3 and Lightdm

**Comment by harsan81** [comment]
From what I've seen here:
https://wiki.archlinux.org/index.php/Laptop/Acer
Apparently Acer Nitro has one model (Nitro VN7-792G-751Y) which HDMI doesn't work.

Here is the link in which I found my solution.
https://askubuntu.com/questions/1105332/external-monitor-not-working-ubuntu-nvidia/1134579#1134579

Might have the same problem as yours:
https://www.reddit.com/r/pop_os/comments/b4mqpo/setting_nvidiadrmnomodeset_to_1_disables_external/

Have you tried using DisplayPort instead?

Oh yeah, try posting this issue on reddit, as there are more active people there. Other users might be able to help.

**Comment by sindile** [comment]
I am going to close this issue.
I am now using a Thunderbolt to HDMI adapter and it works.

**Comment by igauravbhatnagar** [comment]
Well, this is still an issue and must be re-opened unless already done.
There is still an issue with popOs failing to display anything on the second monitor with HDMI or TypeC.
Xrandr detects both though.
Make: Lenovo Legion 5P

**Comment by MURTOMAASORTAJA** [comment]
> I am going to close this issue. I am now using a Thunderbolt to HDMI adapter and it works.

It's still a raging issue :p

**Comment by T100D** [comment]
Had the same problem, with a chromebook and popos to a monitor over hdmi, after switching to display port is was working. Might have to do with the cable used and the possibilities supported bij the cable/port types.

**Comment by sscansan** [comment]
This issue is still going on... 
Fresh install of Pop_OS! 22.04.
I have the same problem. 

Don't ask me how, but I can get around increasing the refresh rate at least at 120Hz of one of the two external monitors (BenQ). When all three are at 60Hz then one of the external (Dell) is not working.
![IMG_20230419_004029.jpg](https://user-images.githubusercontent.com/75729718/232920552-063907a7-7e82-4f96-bc94-c7157f2125a3.jpg)

Setup: 
- 1. Legion 5 Pro
- 2. BenQ 2710R
- 3. Dell P2720D
- Dell WD19TBS dock

**Comment by djgamerr** [comment]
Dell G15 5515 with WD19 dock (Nvidia 3050ti)
Laptops HDMI works all the time
when i start using my monitors with the dock, one of the following 3 scenarios will happen:

1) if i use DP, monitors will work fine for some time, then they will stop getting signal for a couple of seconds, then they will MAYBE come back. If they dont I have to power-cycle the monitor to get it to show anything again. The monitor also has a chance to work in 59.95Hz refresh rate instead of 165Hz, to get this sorted out i have to unplug the dock and plug it back in.

2) if i use laptops HDMI for one display, and docks HDMI for another then the monitor connected to the dock will work all the time, if it turns on that is. Power cycling the monitor doesnt do anything, its as if its not getting anything through the cable. OS detects the monitor though. I have to shuffle with the display setting, save them to force a refresh, then revert the changes and maybe the monitor will turn on. When it turns on it works fine.

3) if i connect both monitors to the dock, depending on the DP/HDMI cable - one of the previous two scenarios will occur.



I tried a lot of solutions to get this resolved but to no avail.
1) reinstall newer/older drivers - nothing
2) try different cables - nothing
3) xorg.conf settings found on random forums only made it worse
4) jounralctl and dmesg only shows as the monitor is disconnected (DP), and shows nothing (HDMI)
5) using xrandr to set resolution did nothing to bring it back
6) xset -dpms did nothing in both cases

If i can provide anything else regarding this issue, please let me know, as I would also like to get this resolved.

**Comment by yatagan** [comment]
Fixed by changing from Dynamic Graphics to Discrete Graphics in BIOS
