### ISSUE TITLE
Recovery partition and boot options are not installed during automatic partitioning

### ISSUE THREAD

**Issue by jetole** [pop-os/pop#936]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Unknown.

**Issue/Bug Description:**
When doing a clean install of Pop OS 20.04 from bootable media (USB drive containing ISO installed via `dd` command) and choosing to use the default / automatic partitioning, no recovery partition is created. I verified this using the GUI disks util and fdisk from the cli. The only partitions are the primary partition containing /, /boot, /home, etc on sda1, and the second partition for swap os on sda2. I reviewed the boot loader startup menu and the only options were to boot Pop or advanced options, which contained options such as which kernel. This was expected since I already knew there was no recovery partition.

**Steps to reproduce (if you know):**
Install a fresh Pop OS installation and select the option for automatic partitioning.

**Expected behavior:**
That the disk will be partitioned to have a recovery partition which will, at least, be accessible from the boot loader menu. The recovery partition should be a 4GB fat32 partition that contains the original installation media so that I can re-install or perform maintance as if I was booting from the original installation media but without needing the original installation media.

**Other Notes:**
This is non OEM hardware (custom built) but I was lead to believe this should exist on any Pop OS installation. This didn't appear when testing the latest beta on VirtualBox VM before the release but I considered or assumed that maybe it was intentionally disabled on the beta release or that the install determined it was on a VM and didn't need to create the recovery partition.

**Comment by polyurethanegoose** [comment]
I think that on the latest Pop! OS there is no recovery partition. All recovery files are put in the `/recovery` directory - but only when installed with UEFI boot. It looks like the issue here is that installer does not create the `/recovery` directory (with special boot option) on legacy BIOS installations. You've mentioned using Virtualbox - check if your VM is using UEFI. The "Pop!_OS Recovery" is only showed within UEFI Boot Menu..

**Comment by jetole** [comment]
Now I'm using hardware. Core i7 on BIOS.

**Comment by jacobgkau** [comment]
> Now I'm using hardware. Core i7 on BIOS.

It's as @polyurethanegoose said-- the Recovery partition is not created for legacy BIOS installations (which use GRUB), only UEFI installations (which use systemd-boot). This is expected behavior.

To clarify one other thing, you're correct that Recovery (when present) is a separate partition, not a directory like @polyurethanegoose said. The Recovery partition is _mounted_ at /recovery when booted into the main system, which allows for pop-upgrade to access and update Recovery files, etc.

I'm not aware of plans to backport Recovery to legacy BIOS systems, since System76 and all other major manufacturers ship UEFI-capable computers. If you must use legacy BIOS mode, the workaround in the event that you need to recover your system would be using a USB live disk, since the Recovery partition is essentially just a copy of the ISO.

**Comment by jetole** [comment]
Thanks for the update.

*
:: Sincerely,
:: Joseph E. Tole*
