### ISSUE TITLE
Media key's turn on monitor

### ISSUE THREAD

**Issue by lerker100** [pop-os/pop#94]
**Version**
Pos!_OS 17.10

**Issue/Bug Description**
Monitor comes on when changing the volume.

**Steps to reproduce (if you know)**
Press the super key and l
then using the media key's on the keyboard change the volume.

**Expected behavior**
When changing the volume the monitor don't turn on.

**Comment by sramkrishna** [comment]
I'm sorry, but could you provide a little more information on what your setup is?  This seems like the correct behavior that a monitor would wake up if keys are typed.

**Comment by lerker100** [comment]
On the lock screen if you turn up the volume with the media's on your keyboard it turns on the monitor, is that intended?

**Comment by sramkrishna** [comment]
Sorry, for the late response.  What situation is the monitor in?  Is it power saving mode?

**Comment by WatchMkr** [comment]
Yes, it is the intended behavior that the screen turns on for any key press.

**Comment by lerker100** [comment]
I'm talking about volume keys not normal key's

**Comment by WatchMkr** [comment]
I understand. I don't think there's a distinction. My thinking on it - If someone presses any key while the computer is on, the display should turn on. Otherwise the user may suspect something is wrong with their computer. Some users may also want or expect to see the volume indicator when they press the media key even if the display is off.

**Comment by lerker100** [comment]
ok, I guess that makes sense.
