### ISSUE TITLE
Unable to move windows between workspaces w/ external monitor + tiling

### ISSUE THREAD

**Issue by julianlam** [pop-os/pop#987]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Issue/Bug Description:**

With tiling enabled, and when I have an external monitor connected, moving windows between workspaces does not work. The window animated as though it were moving between workspaces, but then snaps back into place in the same workspace.

**Comment by duboisf** [comment]
@julianlam I think you mean _monitors_ instead of workspaces? If so, I have the same issue. Here's an example where if tiling is enabled I can't use `Shift+Super+Right` to move the window to the right monitor (notice in the video that after I disable tiling it works):

![move_window_problem](https://user-images.githubusercontent.com/169247/83656600-bdb5c700-a58d-11ea-918f-c7c3af961781.gif)

```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Comment by julianlam** [comment]
Ah, actually I think that's a different issue. The original issue (moving windows between workspaces) seems to be resolved now, after an update.

I'd recommend opening up a new issue :smile:
